DEFINE SCHEMA_OWNER_NAME = PEONY_OWNER;
DEFINE SCHEMA_OWNER_PASSWORD = 'master#0503';
DEFINE TABLESPACE_NAME = PEONY_OWNER_DATA;
DEFINE TEMP_TABLESPACE_NAME = PEONY_OWNER_TEMP;
DEFINE TABLESPACE_FILE_NAME = 'PEONY_OWNER_DATA.dat';
DEFINE TEMP_TABLESPACE_FILE_NAME = 'PEONY_OWNER_TEMP.dat';



--Clean up script; Delete everthing in the owner schema
DROP USER &&SCHEMA_OWNER_NAME CASCADE;

--Delete all the tablespaces
DROP TABLESPACE &&TABLESPACE_NAME
  INCLUDING CONTENTS AND DATAFILES
  CASCADE CONSTRAINTS;
  
DROP TABLESPACE &&TEMP_TABLESPACE_NAME
  INCLUDING CONTENTS AND DATAFILES
  CASCADE CONSTRAINTS;

EXIT COMMIT;