------ DROP ALL OBJECTS -------

BEGIN
  FOR tableObj in (
    select 'drop table "' || object_name || '" cascade constraints purge ' str
    
    from all_objects
    where generated = 'N' and object_type = 'TABLE' and owner = 'PNY_CONAGEN_DBO'
  )
  LOOP
    EXECUTE IMMEDIATE ('' || tableObj.str);
  END LOOP;


  FOR userObj in (
    select 'drop '||object_type||' "' || object_name || '" ' str
    
    from all_objects
    where generated = 'N' and owner = 'PNY_CONAGEN_DBO'
  )
  LOOP
    EXECUTE IMMEDIATE ('' || userObj.str);
  END LOOP;

END;






----- Sequences ------
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_assembly_op_input"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_project"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 396 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_preset"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_plate_well"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 65 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_plate_set"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_plate"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_part_tag"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 174 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_part"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 12068 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_master"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 842 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_lock"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 39461 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_j5run_construct"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1757 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_j5run"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2048 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_group_user"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 339 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_group"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 319 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_eugene_rule"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 690 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_devicedesign"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3712 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_design_ruleset"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_design_rule_tag"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_design_rule"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 361 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_dd_part"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4130 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_custom_setting"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 261 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_custom_j5parameters"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_custom_field_value"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 12261 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_custom_field"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 401 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_attached_tag"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 603 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_attached_design_ruleset"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_activity_log"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 28944442 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_access_control"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 158622 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_DE_bin_cell"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 28616 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_DE_bin"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7111 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_user_role"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3924 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_user"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1102 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_tag_access"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1665 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_tag"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 373 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_strain_plasmid"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 661 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_strain"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1314 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_sequence_j5run"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 741 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_sequence"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21902 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_seq_feature"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 194195 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_seq_blacklist"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_role"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 66 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_protocol"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2559 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_protein_feature"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_protein"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 827 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_project"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1277 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_preset"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 322 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_plate_well"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 65 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_plate_set"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_plate"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_part_tag"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 726 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_part"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 13140 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_master"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1278 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_lock"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8902 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_j5run_construct"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2374 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_j5run"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2232 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_group_user"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 673 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_group"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 263 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_eugene_rule"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1308 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_devicedesign"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3135 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_design_ruleset"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 643 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_design_rule_tag"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 464 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_design_rule"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 846 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_dd_part"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8764 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_custom_setting"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 202 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_custom_j5parameters"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_custom_field_value"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 17445 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_custom_field"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1270 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_clob_buffer"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 35931 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_attached_tag"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2189 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_attached_design_ruleset"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 582 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_access_control"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 421285 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_DE_bin_cell"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 44167 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_DE_bin"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 15620 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_winston"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 877 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_user_role"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2101 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_user"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3299 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_tag_access"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 126 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_tag"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 304 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_strain_plasmid"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 420 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_strain"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 678 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_sequence_j5run"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_sequence"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 16308 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_seq_feature"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81758 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_seq_blacklist"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 39 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_role"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_protocol"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2020 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_protein_feature"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_protein"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 646 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_assembly_run"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_assembly_operation"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_assembly_op_output"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."sz_assembly_op_input"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_assembly_run"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_assembly_operation"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  "PNY_CONAGEN_DBO"."s_assembly_op_output"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;


----- Tables ------
CREATE TABLE "PNY_CONAGEN_DBO"."attached_design_ruleset" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_attached_design_ruleset"."NEXTVAL" NOT NULL ENABLE ,
	"devicedesign_id" NUMBER NOT NULL ENABLE ,
	"design_ruleset_id" NUMBER NOT NULL ENABLE ,
	"dateCreated" DATE ,
	"dateModified" DATE ,
	"shouldFilter" VARCHAR2(1 BYTE) ,
	"shouldValidate" VARCHAR2(1 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."access_control" 
   (
	"acId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_access_control"."NEXTVAL" NOT NULL ENABLE ,
	"objectId" NUMBER NOT NULL ENABLE ,
	"objectName" VARCHAR2(50 BYTE) NOT NULL ENABLE ,
	"userId" NUMBER ,
	"groupId" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"creatorId" NUMBER ,
	"dependsOn" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."DE_bin_cell" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_DE_bin_cell"."NEXTVAL" NOT NULL ENABLE ,
	"index" NUMBER ,
	"fas" VARCHAR2(256 BYTE) ,
	"de_bin_id" NUMBER ,
	"part_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."DE_bin" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_DE_bin"."NEXTVAL" NOT NULL ENABLE ,
	"directionForward" NUMBER ,
	"dsf" NUMBER ,
	"fro" NUMBER ,
	"extra5PrimeBps" VARCHAR2(256 BYTE) ,
	"extra3PrimeBps" VARCHAR2(256 BYTE) ,
	"binName" VARCHAR2(256 BYTE) ,
	"iconID" VARCHAR2(256 BYTE) ,
	"devicedesign_id" NUMBER ,
	"DEIndex" NUMBER(*,0) ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_sequence" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_sequence"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"FQDN" VARCHAR2(512 BYTE) ,
	"hash" VARCHAR2(256 BYTE) ,
	"circular" NUMBER ,
	"description" VARCHAR2(512 BYTE) ,
	"size" NUMBER ,
	"user_id" NUMBER ,
	"name" VARCHAR2(256 BYTE) ,
	"sequence" CLOB ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"shared_repo" VARCHAR2(400 BYTE) ,
	"type" VARCHAR2(16 BYTE) ,
	"molecule_type" VARCHAR2(400 BYTE) ,
	"j5run_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_seq_feature" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_seq_feature"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"name" VARCHAR2(256 BYTE) ,
	"type" VARCHAR2(128 BYTE) ,
	"start" NUMBER ,
	"end" NUMBER ,
	"sequence_id" NUMBER ,
	"strand" NUMBER ,
	"notes" VARCHAR2(4000 BYTE) ,
	"protein_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_seq_blacklist" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_seq_blacklist"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"user_id" NUMBER ,
	"sequence_id" NUMBER ,
	"id" NUMBER ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_role" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_role"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"name" VARCHAR2(400 BYTE) ,
	"description" VARCHAR2(2000 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_protocol" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_protocol"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"user_id" NUMBER ,
	"author" VARCHAR2(256 BYTE) ,
	"htmlContent" CLOB ,
	"assemblyMethods" VARCHAR2(4000 BYTE) ,
	"name" VARCHAR2(256 BYTE) ,
	"contact" VARCHAR2(256 BYTE) ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"version" VARCHAR2(256 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_protein_feature" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_protein_feature"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"name" VARCHAR2(256 BYTE) ,
	"type" VARCHAR2(128 BYTE) ,
	"start" NUMBER ,
	"end" NUMBER ,
	"notes" VARCHAR2(4000 BYTE) ,
	"protein_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"prot_feature_type_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_protein" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_protein"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"FQDN" VARCHAR2(512 BYTE) ,
	"hash" VARCHAR2(256 BYTE) ,
	"circular" NUMBER ,
	"description" VARCHAR2(512 BYTE) ,
	"size" NUMBER ,
	"user_id" NUMBER ,
	"name" VARCHAR2(256 BYTE) ,
	"sequence" CLOB ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"shared_repo" VARCHAR2(400 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_project" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_project"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"name" VARCHAR2(256 BYTE) ,
	"user_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_preset" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_preset"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"presetName" VARCHAR2(256 BYTE) ,
	"j5parameters" VARCHAR2(4000 BYTE) ,
	"user_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_plate_well" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_plate_well"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"id" NUMBER ,
	"plate_id" NUMBER ,
	"name" VARCHAR2(400 BYTE) ,
	"sampleName" VARCHAR2(400 BYTE) ,
	"concentration" NUMBER ,
	"volume" NUMBER ,
	"dateModified" TIMESTAMP (6) ,
	"dateCreated" TIMESTAMP (6) ,
	"user_id" NUMBER ,
	"sourceMaterial" VARCHAR2(4000 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_plate_set" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_plate_set"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"id" NUMBER ,
	"name" VARCHAR2(400 BYTE) ,
	"sampleType" VARCHAR2(400 BYTE) ,
	"dateModified" TIMESTAMP (6) ,
	"dateCreated" TIMESTAMP (6) ,
	"user_id" NUMBER ,
	"plateFormat" VARCHAR2(400 BYTE) ,
	"assembly_operation_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_plate" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_plate"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"id" NUMBER ,
	"plate_set_id" NUMBER ,
	"name" VARCHAR2(400 BYTE) ,
	"dateModified" TIMESTAMP (6) ,
	"dateCreated" TIMESTAMP (6) ,
	"user_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_part_tag" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_part_tag"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"id" NUMBER ,
	"part_id" NUMBER ,
	"tag_id" NUMBER ,
	"dateModified" TIMESTAMP (6) ,
	"dateCreated" TIMESTAMP (6) ,
	"user_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_part" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_part"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"definitionHash" VARCHAR2(64 BYTE) ,
	"FQDN" VARCHAR2(512 BYTE) ,
	"genbankStartBP" NUMBER ,
	"endBP" NUMBER ,
	"revComp" NUMBER ,
	"directionForward" NUMBER ,
	"features" VARCHAR2(1028 BYTE) ,
	"iconID" VARCHAR2(256 BYTE) ,
	"size" NUMBER ,
	"name" VARCHAR2(256 BYTE) ,
	"user_id" NUMBER ,
	"sequence_id" NUMBER ,
	"partSource" VARCHAR2(256 BYTE) ,
	"preferred3PrimeOverhangs" VARCHAR2(256 BYTE) ,
	"preferred5PrimeOverhangs" VARCHAR2(256 BYTE) ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_master" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_master"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"masterDirectSynthesesList" CLOB ,
	"masterOligoList" CLOB ,
	"masterPlasmidList" CLOB ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"user_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_lock" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_lock"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"id" NUMBER ,
	"objectId" NUMBER ,
	"objectName" VARCHAR2(20 BYTE) ,
	"locked_by" NUMBER ,
	"dateModified" TIMESTAMP (6) ,
	"dateCreated" TIMESTAMP (6) ,
	"lockExpires" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_j5run_construct" 
   (
	"sequenceblob" CLOB ,
	"id" NUMBER ,
	"dateModified" TIMESTAMP (6) ,
	"dateCreated" TIMESTAMP (6) ,
	"user_id" NUMBER ,
	"name" VARCHAR2(400 BYTE) ,
	"j5run_id" NUMBER ,
	"part_names_string" CLOB ,
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_j5run_construct"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"sizeBP" NUMBER ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_j5run" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_j5run"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"assemblyMethod" VARCHAR2(256 BYTE) ,
	"assemblyType" VARCHAR2(256 BYTE) ,
	"date" DATE ,
	"devicedesign_name" VARCHAR2(256 BYTE) ,
	"endDate" DATE ,
	"name" VARCHAR2(256 BYTE) ,
	"status" VARCHAR2(256 BYTE) ,
	"user_id" NUMBER ,
	"devicedesign_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"clientTimeDiff" VARCHAR2(256 BYTE) ,
	"project_id" NUMBER ,
	"protocol_id" NUMBER ,
	"results" CLOB ,
	"j5output" CLOB ,
	"preset_id" NUMBER ,
	"warnings" CLOB ,
	"error" CLOB
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_group_user" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_group_user"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"group_id" NUMBER ,
	"user_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_group" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_group"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"name" VARCHAR2(400 BYTE) ,
	"description" VARCHAR2(4000 BYTE) ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"user_id" NUMBER ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_eugene_rule" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_eugene_rule"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"operand1_id" NUMBER ,
	"operand2_id" NUMBER ,
	"name" VARCHAR2(256 BYTE) ,
	"originalRuleLine" VARCHAR2(256 BYTE) ,
	"negationOperator" NUMBER ,
	"operand2IsNumber" NUMBER ,
	"operand2Number" NUMBER ,
	"compositionalOperator" VARCHAR2(256 BYTE) ,
	"devicedesign_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_devicedesign" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_devicedesign"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"name" VARCHAR2(256 BYTE) ,
	"combinatorial" NUMBER ,
	"isCircular" NUMBER ,
	"user_id" NUMBER ,
	"project_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"assemblyMethod" VARCHAR2(256 BYTE) ,
	"paramPreset" VARCHAR2(256 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_design_rule_tag" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_design_rule_tag"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"id" NUMBER ,
	"design_rule_id" NUMBER ,
	"tag_id" NUMBER ,
	"existence" VARCHAR2(32 BYTE) ,
	"dateCreated" DATE ,
	"dateModified" DATE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_design_rule" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_design_rule"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"id" NUMBER ,
	"name" VARCHAR2(256 BYTE) ,
	"user_id" NUMBER ,
	"dateModified" DATE ,
	"dateCreated" DATE ,
	"type" VARCHAR2(256 BYTE) ,
	"regex" VARCHAR2(256 BYTE) ,
	"design_ruleset_id" NUMBER ,
	"columnName" VARCHAR2(256 BYTE) ,
	"columnIndex" VARCHAR2(32 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_dd_part" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_dd_part"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"devicedesign_id" NUMBER ,
	"part_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_custom_setting" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_custom_setting"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"id" NUMBER ,
	"key" VARCHAR2(400 BYTE) ,
	"value" CLOB ,
	"valueType" VARCHAR2(400 BYTE) ,
	"configCategory" VARCHAR2(400 BYTE) ,
	"dateModified" DATE ,
	"dateCreated" DATE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_custom_j5parameters" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_custom_j5parameters"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"name" VARCHAR2(256 BYTE) ,
	"user_id" NUMBER ,
	"suppress_primer_annotations" NUMBER ,
	"suppress_pure_primers" NUMBER ,
	"hmlgy_max_fraction_mismatches" NUMBER ,
	"hmlgy_min_length_bps" NUMBER ,
	"output_seq_format" VARCHAR2(256 BYTE) ,
	"mispriming_oligo_conc" NUMBER ,
	"mispriming_salt_conc" NUMBER ,
	"mispriming_min_tm" NUMBER ,
	"mispriming_3pbp_to_warn_if_hit" NUMBER ,
	"primer_dna_conc" NUMBER ,
	"primer_salt_corrections" NUMBER ,
	"primer_tm_santalucia" NUMBER ,
	"primer_pair_max_compl_end_th" NUMBER ,
	"primer_pair_max_compl_any_th" NUMBER ,
	"primer_max_self_end_th" NUMBER ,
	"primer_max_self_any_th" NUMBER ,
	"primer_max_diff_tm" NUMBER ,
	"primer_max_tm" NUMBER ,
	"primer_min_tm" NUMBER ,
	"primer_max_size" NUMBER ,
	"primer_min_size" NUMBER ,
	"primer_gc_clamp" NUMBER ,
	"dir_synth_min_cost_per_piece" NUMBER ,
	"dir_synth_cost_per_bp" NUMBER ,
	"min_pcr_product_bps" NUMBER ,
	"oligo_max_len_no_page_pur_bps" NUMBER ,
	"oligo_page_pur_cost_per_piece" NUMBER ,
	"oligo_synthesis_cost_per_bp" NUMBER ,
	"max_ids_ggate_overhangs_cmptbl" NUMBER ,
	"ggate_termini_extra_seq" VARCHAR2(256 BYTE) ,
	"ggate_recognition_seq" VARCHAR2(256 BYTE) ,
	"ggate_overhang_bps" NUMBER ,
	"min_fragment_size_gibson_bps" NUMBER ,
	"max_oligo_length_bps" NUMBER ,
	"gibson_overlap_max_tm" NUMBER ,
	"gibson_overlap_min_tm" NUMBER ,
	"gibson_overlap_bps" NUMBER ,
	"master_plasmid_num_of_digits" NUMBER ,
	"master_oligo_num_of_digits" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_custom_field_value" 
   (
	"id" NUMBER ,
	"custom_field_id" NUMBER ,
	"dateModified" DATE ,
	"dateCreated" DATE ,
	"objectId" NUMBER ,
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_custom_field_value"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(20 BYTE) ,
	"dateLogged" DATE DEFAULT SYSDATE NOT NULL ENABLE ,
	"objectName" VARCHAR2(50 BYTE) ,
	"valueString" VARCHAR2(4000 BYTE) ,
	"valueNumber" NUMBER ,
	"valueFlag" NUMBER ,
	"valueDate" DATE ,
	"user_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_custom_field" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_custom_field"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"id" NUMBER ,
	"objectName" VARCHAR2(50 BYTE) ,
	"name" VARCHAR2(400 BYTE) ,
	"required" NUMBER ,
	"dateCreated" DATE ,
	"dateModified" DATE ,
	"searchable" NUMBER ,
	"dataType" VARCHAR2(50 BYTE) ,
	"defaultValueString" VARCHAR2(4000 BYTE) ,
	"defaultValueNumber" NUMBER ,
	"defaultValueFlag" NUMBER ,
	"defaultValueDate" DATE ,
	"isAdminCreated" NUMBER ,
	"user_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_attached_tag" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_attached_tag"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"id" NUMBER ,
	"tagged_data_id" NUMBER ,
	"tag_id" NUMBER ,
	"tagged_data_type" VARCHAR2(400 BYTE) ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"filterLogic" VARCHAR2(400 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_attached_design_ruleset" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_attached_design_ruleset"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"id" NUMBER ,
	"devicedesign_id" NUMBER ,
	"design_ruleset_id" NUMBER ,
	"dateCreated" DATE ,
	"dateModified" DATE ,
	"shouldFilter" VARCHAR2(1 BYTE) ,
	"shouldValidate" VARCHAR2(1 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_activity_log" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_activity_log"."NEXTVAL" NOT NULL ENABLE ,
	"objectName" VARCHAR2(400 BYTE) ,
	"objectId" NUMBER ,
	"user_id" NUMBER ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"description" VARCHAR2(4000 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"recordsFetched" NUMBER ,
	"rawQuery" CLOB
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_access_control" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_access_control"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"acId" NUMBER ,
	"objectId" NUMBER ,
	"objectName" VARCHAR2(50 BYTE) ,
	"userId" NUMBER ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"creatorId" NUMBER ,
	"dependsOn" NUMBER ,
	"groupId" NUMBER ,
	"dateCreated" TIMESTAMP (6)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_design_ruleset" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_design_ruleset"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"id" NUMBER ,
	"user_id" NUMBER ,
	"name" VARCHAR2(400 BYTE) ,
	"description" VARCHAR2(256 BYTE) ,
	"dateCreated" DATE ,
	"dateModified" DATE ,
	"shouldFilter" VARCHAR2(1 BYTE) ,
	"shouldValidate" VARCHAR2(1 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_winston" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_winston"."NEXTVAL" NOT NULL ENABLE ,
	"user_id" NUMBER ,
	"requestId" VARCHAR2(100 BYTE) ,
	"level" VARCHAR2(400 BYTE) ,
	"message" CLOB ,
	"metadata" CLOB ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"channel" VARCHAR2(400 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_user_role" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_user_role"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"user_id" NUMBER ,
	"role_id" NUMBER ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_user" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_user"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"username" VARCHAR2(256 BYTE) ,
	"password" VARCHAR2(256 BYTE) ,
	"firstName" VARCHAR2(256 BYTE) ,
	"lastName" VARCHAR2(256 BYTE) ,
	"email" VARCHAR2(256 BYTE) ,
	"activationCode" VARCHAR2(256 BYTE) ,
	"groupName" VARCHAR2(256 BYTE) ,
	"groupType" VARCHAR2(256 BYTE) ,
	"lastAccess" DATE ,
	"debugAccess" NUMBER ,
	"verifiedEmail" NUMBER ,
	"activated" NUMBER ,
	"token" VARCHAR2(256 BYTE) ,
	"middleName" VARCHAR2(256 BYTE) ,
	"activeFlag" VARCHAR2(1 BYTE) ,
	"phoneNumber" VARCHAR2(64 BYTE) ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"userAccount" VARCHAR2(256 BYTE) ,
	"userRestrictionEnzymeGroups" CLOB ,
	"notificationPref" VARCHAR2(400 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_tag_access" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_tag_access"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"id" NUMBER ,
	"dateModified" DATE ,
	"group_id" NUMBER ,
	"tag_id" NUMBER ,
	"dateCreated" DATE ,
	"user_id" NUMBER ,
	"global" NUMBER(1,0)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_tag" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_tag"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"name" VARCHAR2(400 BYTE) ,
	"color" VARCHAR2(400 BYTE) ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"user_id" NUMBER ,
	"id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_strain_plasmid" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_strain_plasmid"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"strain_id" NUMBER ,
	"sequence_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_strain" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_strain"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"FQDN" VARCHAR2(512 BYTE) ,
	"selectionMarkers" VARCHAR2(1024 BYTE) ,
	"principalInvestigator" VARCHAR2(512 BYTE) ,
	"intellectualProperty" VARCHAR2(1024 BYTE) ,
	"references" VARCHAR2(1024 BYTE) ,
	"summary" VARCHAR2(4000 BYTE) ,
	"keywords" VARCHAR2(512 BYTE) ,
	"genotype" VARCHAR2(512 BYTE) ,
	"links" VARCHAR2(512 BYTE) ,
	"parentStrain" VARCHAR2(512 BYTE) ,
	"bioSafetyLevel" VARCHAR2(512 BYTE) ,
	"status" VARCHAR2(64 BYTE) ,
	"fundingSource" VARCHAR2(512 BYTE) ,
	"creatorEmail" VARCHAR2(256 BYTE) ,
	"creator" VARCHAR2(256 BYTE) ,
	"alias" VARCHAR2(256 BYTE) ,
	"name" VARCHAR2(512 BYTE) ,
	"user_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_sequence_j5run" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_sequence_j5run"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"sequence_id" NUMBER ,
	"j5run_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"construct_id" NUMBER ,
	"id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_DE_bin_cell" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_DE_bin_cell"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"index" NUMBER ,
	"fas" VARCHAR2(256 BYTE) ,
	"de_bin_id" NUMBER ,
	"part_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_DE_bin" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_DE_bin"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"id" NUMBER ,
	"directionForward" NUMBER ,
	"dsf" NUMBER ,
	"fro" NUMBER ,
	"extra5PrimeBps" VARCHAR2(256 BYTE) ,
	"extra3PrimeBps" VARCHAR2(256 BYTE) ,
	"binName" VARCHAR2(256 BYTE) ,
	"iconID" VARCHAR2(256 BYTE) ,
	"devicedesign_id" NUMBER ,
	"DEIndex" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."user_role" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_user_role"."NEXTVAL" NOT NULL ENABLE ,
	"user_id" NUMBER NOT NULL ENABLE ,
	"role_id" NUMBER NOT NULL ENABLE ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."user" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_user"."NEXTVAL" NOT NULL ENABLE ,
	"username" VARCHAR2(256 BYTE) ,
	"password" VARCHAR2(256 BYTE) ,
	"firstName" VARCHAR2(256 BYTE) ,
	"lastName" VARCHAR2(256 BYTE) ,
	"email" VARCHAR2(256 BYTE) ,
	"activationCode" VARCHAR2(256 BYTE) ,
	"groupName" VARCHAR2(256 BYTE) ,
	"groupType" VARCHAR2(256 BYTE) ,
	"lastAccess" DATE ,
	"debugAccess" NUMBER ,
	"verifiedEmail" NUMBER ,
	"activated" NUMBER ,
	"token" VARCHAR2(256 BYTE) ,
	"middleName" VARCHAR2(256 BYTE) ,
	"activeFlag" VARCHAR2(1 BYTE) ,
	"phoneNumber" VARCHAR2(64 BYTE) ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"userAccount" VARCHAR2(256 BYTE) ,
	"userRestrictionEnzymeGroups" CLOB ,
	"notificationPref" VARCHAR2(400 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."tag_access" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_tag_access"."NEXTVAL" NOT NULL ENABLE ,
	"dateModified" DATE ,
	"group_id" NUMBER ,
	"tag_id" NUMBER ,
	"dateCreated" DATE ,
	"user_id" NUMBER ,
	"global" NUMBER(1,0)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."tag" 
   (
	"name" VARCHAR2(400 BYTE) ,
	"color" VARCHAR2(400 BYTE) ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"user_id" NUMBER ,
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_tag"."NEXTVAL" NOT NULL ENABLE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."strain_plasmid" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_strain_plasmid"."NEXTVAL" NOT NULL ENABLE ,
	"strain_id" NUMBER ,
	"sequence_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."strain" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_strain"."NEXTVAL" NOT NULL ENABLE ,
	"FQDN" VARCHAR2(512 BYTE) ,
	"selectionMarkers" VARCHAR2(1024 BYTE) ,
	"principalInvestigator" VARCHAR2(512 BYTE) ,
	"intellectualProperty" VARCHAR2(1024 BYTE) ,
	"references" VARCHAR2(1024 BYTE) ,
	"summary" VARCHAR2(4000 BYTE) ,
	"keywords" VARCHAR2(512 BYTE) ,
	"genotype" VARCHAR2(512 BYTE) ,
	"links" VARCHAR2(512 BYTE) ,
	"parentStrain" VARCHAR2(512 BYTE) ,
	"bioSafetyLevel" VARCHAR2(512 BYTE) ,
	"status" VARCHAR2(64 BYTE) ,
	"fundingSource" VARCHAR2(512 BYTE) ,
	"creatorEmail" VARCHAR2(256 BYTE) ,
	"creator" VARCHAR2(256 BYTE) ,
	"alias" VARCHAR2(256 BYTE) ,
	"name" VARCHAR2(512 BYTE) ,
	"user_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."sequence_j5run" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_sequence_j5run"."NEXTVAL" NOT NULL ENABLE ,
	"sequence_id" NUMBER ,
	"j5run_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"construct_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."sequence" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_sequence"."NEXTVAL" NOT NULL ENABLE ,
	"FQDN" VARCHAR2(512 BYTE) ,
	"hash" VARCHAR2(256 BYTE) ,
	"circular" NUMBER ,
	"description" VARCHAR2(512 BYTE) ,
	"size" NUMBER ,
	"user_id" NUMBER ,
	"name" VARCHAR2(256 BYTE) ,
	"sequence" CLOB ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"shared_repo" VARCHAR2(400 BYTE) ,
	"type" VARCHAR2(16 BYTE) ,
	"molecule_type" VARCHAR2(400 BYTE) ,
	"j5run_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."seq_feature" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_seq_feature"."NEXTVAL" NOT NULL ENABLE ,
	"name" VARCHAR2(256 BYTE) ,
	"type" VARCHAR2(128 BYTE) ,
	"start" NUMBER ,
	"end" NUMBER ,
	"sequence_id" NUMBER ,
	"strand" NUMBER(*,0) ,
	"notes" VARCHAR2(4000 BYTE) ,
	"protein_id" NUMBER(*,0) ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."seq_blacklist" 
   (
	"user_id" NUMBER(*,0) ,
	"sequence_id" NUMBER(*,0) ,
	"id" NUMBER(*,0) DEFAULT "PNY_CONAGEN_DBO"."s_seq_blacklist"."NEXTVAL" NOT NULL ENABLE ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."role" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_role"."NEXTVAL" NOT NULL ENABLE ,
	"name" VARCHAR2(400 BYTE) NOT NULL ENABLE ,
	"description" VARCHAR2(2000 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."protocol" 
   (
	"id" NUMBER(*,0) DEFAULT "PNY_CONAGEN_DBO"."s_protocol"."NEXTVAL" NOT NULL ENABLE ,
	"user_id" NUMBER(*,0) ,
	"author" VARCHAR2(256 BYTE) ,
	"htmlContent" CLOB ,
	"assemblyMethods" VARCHAR2(4000 BYTE) ,
	"name" VARCHAR2(256 BYTE) ,
	"contact" VARCHAR2(256 BYTE) ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"version" VARCHAR2(256 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."protein_feature" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_protein_feature"."NEXTVAL" NOT NULL ENABLE ,
	"name" VARCHAR2(256 BYTE) ,
	"type" VARCHAR2(128 BYTE) ,
	"start" NUMBER ,
	"end" NUMBER ,
	"notes" VARCHAR2(4000 BYTE) ,
	"protein_id" NUMBER(*,0) ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"prot_feature_type_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."protein" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_protein"."NEXTVAL" NOT NULL ENABLE ,
	"FQDN" VARCHAR2(512 BYTE) ,
	"hash" VARCHAR2(256 BYTE) ,
	"circular" NUMBER ,
	"description" VARCHAR2(512 BYTE) ,
	"size" NUMBER ,
	"user_id" NUMBER ,
	"name" VARCHAR2(256 BYTE) ,
	"sequence" CLOB ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"shared_repo" VARCHAR2(400 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."project" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_project"."NEXTVAL" NOT NULL ENABLE ,
	"name" VARCHAR2(256 BYTE) ,
	"user_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."preset" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_preset"."NEXTVAL" NOT NULL ENABLE ,
	"presetName" VARCHAR2(256 BYTE) ,
	"j5parameters" VARCHAR2(4000 BYTE) ,
	"user_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."plate_well" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_plate_well"."NEXTVAL" NOT NULL ENABLE ,
	"plate_id" NUMBER ,
	"name" VARCHAR2(400 BYTE) ,
	"sampleName" VARCHAR2(400 BYTE) ,
	"concentration" NUMBER ,
	"volume" NUMBER ,
	"dateModified" TIMESTAMP (6) ,
	"dateCreated" TIMESTAMP (6) ,
	"user_id" NUMBER ,
	"sourceMaterial" VARCHAR2(4000 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."plate_set" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_plate_set"."NEXTVAL" NOT NULL ENABLE ,
	"name" VARCHAR2(400 BYTE) ,
	"sampleType" VARCHAR2(400 BYTE) ,
	"dateModified" TIMESTAMP (6) ,
	"dateCreated" TIMESTAMP (6) ,
	"user_id" NUMBER ,
	"plateFormat" VARCHAR2(400 BYTE) ,
	"assembly_operation_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."plate" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_plate"."NEXTVAL" NOT NULL ENABLE ,
	"plate_set_id" NUMBER ,
	"name" VARCHAR2(400 BYTE) ,
	"dateModified" TIMESTAMP (6) ,
	"dateCreated" TIMESTAMP (6) ,
	"user_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."part_tag" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_part_tag"."NEXTVAL" NOT NULL ENABLE ,
	"part_id" NUMBER ,
	"tag_id" NUMBER ,
	"dateModified" TIMESTAMP (6) ,
	"dateCreated" TIMESTAMP (6) ,
	"user_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."part" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_part"."NEXTVAL" NOT NULL ENABLE ,
	"definitionHash" VARCHAR2(64 BYTE) ,
	"FQDN" VARCHAR2(512 BYTE) ,
	"genbankStartBP" NUMBER ,
	"endBP" NUMBER ,
	"revComp" NUMBER ,
	"directionForward" NUMBER ,
	"features" VARCHAR2(1028 BYTE) ,
	"iconID" VARCHAR2(256 BYTE) ,
	"size" NUMBER ,
	"name" VARCHAR2(256 BYTE) ,
	"user_id" NUMBER ,
	"sequence_id" NUMBER ,
	"partSource" VARCHAR2(256 BYTE) ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"preferred3PrimeOverhangs" VARCHAR2(256 BYTE) ,
	"preferred5PrimeOverhangs" VARCHAR2(256 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."master" 
   (
	"user_id" NUMBER ,
	"masterDirectSynthesesList" CLOB ,
	"masterOligoList" CLOB ,
	"masterPlasmidList" CLOB ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_master"."NEXTVAL" NOT NULL ENABLE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."lock" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_lock"."NEXTVAL" NOT NULL ENABLE ,
	"objectId" NUMBER ,
	"objectName" VARCHAR2(20 BYTE) ,
	"locked_by" NUMBER ,
	"dateModified" TIMESTAMP (6) ,
	"dateCreated" TIMESTAMP (6) ,
	"lockExpires" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."j5run_construct" 
   (
	"sequenceblob" CLOB ,
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_j5run_construct"."NEXTVAL" NOT NULL ENABLE ,
	"dateModified" TIMESTAMP (6) ,
	"dateCreated" TIMESTAMP (6) ,
	"user_id" NUMBER ,
	"name" VARCHAR2(400 BYTE) ,
	"j5run_id" NUMBER ,
	"part_names_string" CLOB ,
	"sizeBP" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."j5run" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_j5run"."NEXTVAL" NOT NULL ENABLE ,
	"assemblyMethod" VARCHAR2(256 BYTE) ,
	"assemblyType" VARCHAR2(256 BYTE) ,
	"date" DATE ,
	"devicedesign_name" VARCHAR2(256 BYTE) ,
	"endDate" DATE ,
	"name" VARCHAR2(256 BYTE) ,
	"status" VARCHAR2(256 BYTE) ,
	"user_id" NUMBER ,
	"devicedesign_id" NUMBER(*,0) ,
	"protocol_id" NUMBER(*,0) ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"results" CLOB ,
	"j5output" CLOB ,
	"project_id" NUMBER(38,0) ,
	"clientTimeDiff" VARCHAR2(256 BYTE) ,
	"preset_id" NUMBER ,
	"warnings" CLOB ,
	"error" CLOB
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."group_user" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_group_user"."NEXTVAL" NOT NULL ENABLE ,
	"group_id" NUMBER NOT NULL ENABLE ,
	"user_id" NUMBER NOT NULL ENABLE ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."group" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_group"."NEXTVAL" NOT NULL ENABLE ,
	"name" VARCHAR2(400 BYTE) ,
	"description" VARCHAR2(4000 BYTE) ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"user_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."eugene_rule" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_eugene_rule"."NEXTVAL" NOT NULL ENABLE ,
	"operand1_id" NUMBER ,
	"operand2_id" NUMBER ,
	"name" VARCHAR2(256 BYTE) ,
	"originalRuleLine" VARCHAR2(256 BYTE) ,
	"negationOperator" NUMBER ,
	"operand2IsNumber" NUMBER ,
	"operand2Number" NUMBER ,
	"compositionalOperator" VARCHAR2(256 BYTE) ,
	"devicedesign_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."devicedesign" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_devicedesign"."NEXTVAL" NOT NULL ENABLE ,
	"name" VARCHAR2(256 BYTE) ,
	"combinatorial" NUMBER ,
	"isCircular" NUMBER ,
	"user_id" NUMBER ,
	"project_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"assemblyMethod" VARCHAR2(256 BYTE) ,
	"paramPreset" VARCHAR2(256 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."design_ruleset" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_design_ruleset"."NEXTVAL" NOT NULL ENABLE ,
	"name" VARCHAR2(400 BYTE) ,
	"description" VARCHAR2(256 BYTE) ,
	"user_id" NUMBER ,
	"dateCreated" DATE ,
	"dateModified" DATE ,
	"shouldFilter" VARCHAR2(1 BYTE) ,
	"shouldValidate" VARCHAR2(1 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."design_rule_tag" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_design_rule_tag"."NEXTVAL" NOT NULL ENABLE ,
	"design_rule_id" NUMBER NOT NULL ENABLE ,
	"tag_id" NUMBER NOT NULL ENABLE ,
	"existence" VARCHAR2(32 BYTE) ,
	"dateCreated" DATE ,
	"dateModified" DATE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."design_rule" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_design_rule"."NEXTVAL" NOT NULL ENABLE ,
	"name" VARCHAR2(256 BYTE) ,
	"user_id" NUMBER ,
	"dateModified" DATE ,
	"dateCreated" DATE ,
	"type" VARCHAR2(256 BYTE) ,
	"regex" VARCHAR2(256 BYTE) ,
	"design_ruleset_id" NUMBER ,
	"columnName" VARCHAR2(256 BYTE) ,
	"columnIndex" VARCHAR2(32 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."dd_part" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_dd_part"."NEXTVAL" NOT NULL ENABLE ,
	"devicedesign_id" NUMBER ,
	"part_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."custom_setting" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_custom_setting"."NEXTVAL" NOT NULL ENABLE ,
	"key" VARCHAR2(400 BYTE) NOT NULL ENABLE ,
	"value" CLOB ,
	"valueType" VARCHAR2(400 BYTE) ,
	"configCategory" VARCHAR2(400 BYTE) ,
	"dateModified" DATE ,
	"dateCreated" DATE
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."custom_j5parameters" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_custom_j5parameters"."NEXTVAL" NOT NULL ENABLE ,
	"name" VARCHAR2(256 BYTE) ,
	"user_id" NUMBER ,
	"suppress_primer_annotations" NUMBER ,
	"suppress_pure_primers" NUMBER ,
	"hmlgy_max_fraction_mismatches" NUMBER ,
	"hmlgy_min_length_bps" NUMBER ,
	"output_seq_format" VARCHAR2(256 BYTE) ,
	"mispriming_oligo_conc" NUMBER ,
	"mispriming_salt_conc" NUMBER ,
	"mispriming_min_tm" NUMBER ,
	"mispriming_3pbp_to_warn_if_hit" NUMBER ,
	"primer_dna_conc" NUMBER ,
	"primer_salt_corrections" NUMBER ,
	"primer_tm_santalucia" NUMBER ,
	"primer_pair_max_compl_end_th" NUMBER ,
	"primer_pair_max_compl_any_th" NUMBER ,
	"primer_max_self_end_th" NUMBER ,
	"primer_max_self_any_th" NUMBER ,
	"primer_max_diff_tm" NUMBER ,
	"primer_max_tm" NUMBER ,
	"primer_min_tm" NUMBER ,
	"primer_max_size" NUMBER ,
	"primer_min_size" NUMBER ,
	"primer_gc_clamp" NUMBER ,
	"dir_synth_min_cost_per_piece" NUMBER ,
	"dir_synth_cost_per_bp" NUMBER ,
	"min_pcr_product_bps" NUMBER ,
	"oligo_max_len_no_page_pur_bps" NUMBER ,
	"oligo_page_pur_cost_per_piece" NUMBER ,
	"oligo_synthesis_cost_per_bp" NUMBER ,
	"max_ids_ggate_overhangs_cmptbl" NUMBER ,
	"ggate_termini_extra_seq" VARCHAR2(256 BYTE) ,
	"ggate_recognition_seq" VARCHAR2(256 BYTE) ,
	"ggate_overhang_bps" NUMBER ,
	"min_fragment_size_gibson_bps" NUMBER ,
	"max_oligo_length_bps" NUMBER ,
	"gibson_overlap_max_tm" NUMBER ,
	"gibson_overlap_min_tm" NUMBER ,
	"gibson_overlap_bps" NUMBER ,
	"master_plasmid_num_of_digits" NUMBER ,
	"master_oligo_num_of_digits" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."custom_field_value" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_custom_field_value"."NEXTVAL" NOT NULL ENABLE ,
	"custom_field_id" NUMBER NOT NULL ENABLE ,
	"dateCreated" DATE ,
	"dateModified" DATE ,
	"objectId" NUMBER ,
	"objectName" VARCHAR2(50 BYTE) ,
	"valueString" VARCHAR2(4000 BYTE) ,
	"valueNumber" NUMBER ,
	"valueFlag" NUMBER ,
	"valueDate" DATE ,
	"user_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."custom_field" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_custom_field"."NEXTVAL" NOT NULL ENABLE ,
	"objectName" VARCHAR2(50 BYTE) NOT NULL ENABLE ,
	"name" VARCHAR2(400 BYTE) NOT NULL ENABLE ,
	"required" NUMBER(*,0) ,
	"dateCreated" DATE ,
	"dateModified" DATE ,
	"searchable" NUMBER ,
	"dataType" VARCHAR2(50 BYTE) ,
	"defaultValueString" VARCHAR2(4000 BYTE) ,
	"defaultValueNumber" NUMBER ,
	"defaultValueFlag" NUMBER ,
	"defaultValueDate" DATE ,
	"isAdminCreated" NUMBER ,
	"user_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."attached_tag" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_attached_tag"."NEXTVAL" NOT NULL ENABLE ,
	"tagged_data_id" NUMBER ,
	"tag_id" NUMBER ,
	"tagged_data_type" VARCHAR2(400 BYTE) ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"filterLogic" VARCHAR2(400 BYTE)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."clob_buffer" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_clob_buffer"."NEXTVAL" NOT NULL ENABLE ,
	"chunk" VARCHAR2(4000 BYTE) ,
	"bufferId" VARCHAR2(400 BYTE) ,
	"chunkIndex" NUMBER ,
	"dateCreated" TIMESTAMP (6)
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_assembly_run" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_assembly_run"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"id" NUMBER ,
	"name" VARCHAR2(400 BYTE) ,
	"j5run_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"user_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_assembly_operation" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_assembly_operation"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"id" NUMBER ,
	"name" VARCHAR2(400 BYTE) ,
	"assembly_run_id" NUMBER ,
	"description" VARCHAR2(4000 BYTE) ,
	"status" VARCHAR2(400 BYTE) ,
	"operationType" VARCHAR2(400 BYTE) ,
	"index" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"user_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_assembly_op_output" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_assembly_op_output"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"id" NUMBER ,
	"name" VARCHAR2(400 BYTE) ,
	"assembly_operation_id" NUMBER ,
	"jsonValue" CLOB ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"user_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."z_assembly_op_input" 
   (
	"logId" NUMBER DEFAULT "PNY_CONAGEN_DBO"."sz_assembly_op_input"."NEXTVAL" NOT NULL ENABLE ,
	"logSessionId" VARCHAR2(50 BYTE) ,
	"logAction" VARCHAR2(400 BYTE) ,
	"dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE ,
	"id" NUMBER ,
	"assembly_operation_id" NUMBER ,
	"assembly_op_output_id" NUMBER ,
	"name" VARCHAR2(400 BYTE) ,
	"dataType" VARCHAR2(400 BYTE) ,
	"textValue" VARCHAR2(4000 BYTE) ,
	"numericValue" NUMBER ,
	"dateValue" TIMESTAMP (6) ,
	"jsonValue" CLOB ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"user_id" NUMBER ,
	"plate_set_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."assembly_run" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_assembly_run"."NEXTVAL" NOT NULL ENABLE ,
	"name" VARCHAR2(400 BYTE) ,
	"j5run_id" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"user_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."assembly_operation" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_assembly_operation"."NEXTVAL" NOT NULL ENABLE ,
	"name" VARCHAR2(400 BYTE) ,
	"assembly_run_id" NUMBER ,
	"description" VARCHAR2(4000 BYTE) ,
	"status" VARCHAR2(400 BYTE) ,
	"operationType" VARCHAR2(400 BYTE) ,
	"index" NUMBER ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"user_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."assembly_op_output" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_assembly_op_output"."NEXTVAL" NOT NULL ENABLE ,
	"name" VARCHAR2(400 BYTE) ,
	"assembly_operation_id" NUMBER ,
	"jsonValue" CLOB ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"user_id" NUMBER
)   ;
CREATE TABLE "PNY_CONAGEN_DBO"."assembly_op_input" 
   (
	"id" NUMBER DEFAULT "PNY_CONAGEN_DBO"."s_assembly_op_input"."NEXTVAL" NOT NULL ENABLE ,
	"assembly_operation_id" NUMBER ,
	"assembly_op_output_id" NUMBER ,
	"name" VARCHAR2(400 BYTE) ,
	"dataType" VARCHAR2(400 BYTE) ,
	"textValue" VARCHAR2(4000 BYTE) ,
	"numericValue" NUMBER ,
	"dateValue" TIMESTAMP (6) ,
	"jsonValue" CLOB ,
	"dateCreated" TIMESTAMP (6) ,
	"dateModified" TIMESTAMP (6) ,
	"user_id" NUMBER ,
	"plate_set_id" NUMBER
)   ;


----- Table Indexes ------
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."DE_bin_pk" ON "PNY_CONAGEN_DBO"."DE_bin" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."DE_bin_cell_pk" ON "PNY_CONAGEN_DBO"."DE_bin_cell" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."access_control_pk" ON "PNY_CONAGEN_DBO"."access_control" ("acId") 
    ;
CREATE INDEX "PNY_CONAGEN_DBO"."access_control_obj_id_name_idx" ON "PNY_CONAGEN_DBO"."access_control" ("objectId", "objectName") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_assembly_run_pk" ON "PNY_CONAGEN_DBO"."z_assembly_run" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_assembly_operation_pk" ON "PNY_CONAGEN_DBO"."z_assembly_operation" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_assembly_op_input_pk" ON "PNY_CONAGEN_DBO"."z_assembly_op_input" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_assembly_op_output_pk" ON "PNY_CONAGEN_DBO"."z_assembly_op_output" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_eugene_rule_pk" ON "PNY_CONAGEN_DBO"."z_eugene_rule" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_group_pk" ON "PNY_CONAGEN_DBO"."z_group" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_group_user_pk" ON "PNY_CONAGEN_DBO"."z_group_user" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_j5run_pk" ON "PNY_CONAGEN_DBO"."z_j5run" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_j5run_construct_pk" ON "PNY_CONAGEN_DBO"."z_j5run_construct" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_lock_pk" ON "PNY_CONAGEN_DBO"."z_lock" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_master_pk" ON "PNY_CONAGEN_DBO"."z_master" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_part_pk" ON "PNY_CONAGEN_DBO"."z_part" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_part_tag_pk" ON "PNY_CONAGEN_DBO"."z_part_tag" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_plate_pk" ON "PNY_CONAGEN_DBO"."z_plate" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_plate_set_pk" ON "PNY_CONAGEN_DBO"."z_plate_set" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_plate_well_pk" ON "PNY_CONAGEN_DBO"."z_plate_well" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_preset_pk" ON "PNY_CONAGEN_DBO"."z_preset" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_project_pk" ON "PNY_CONAGEN_DBO"."z_project" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_protein_pk" ON "PNY_CONAGEN_DBO"."z_protein" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_protein_feature_pk" ON "PNY_CONAGEN_DBO"."z_protein_feature" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_protocol_pk" ON "PNY_CONAGEN_DBO"."z_protocol" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_role_pk" ON "PNY_CONAGEN_DBO"."z_role" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_seq_blacklist_pk" ON "PNY_CONAGEN_DBO"."z_seq_blacklist" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_seq_feature_pk" ON "PNY_CONAGEN_DBO"."z_seq_feature" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_sequence_pk" ON "PNY_CONAGEN_DBO"."z_sequence" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_sequence_j5run_pk" ON "PNY_CONAGEN_DBO"."z_sequence_j5run" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_strain_pk" ON "PNY_CONAGEN_DBO"."z_strain" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_strain_plasmid_pk" ON "PNY_CONAGEN_DBO"."z_strain_plasmid" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_tag_pk" ON "PNY_CONAGEN_DBO"."z_tag" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_tag_access_pk" ON "PNY_CONAGEN_DBO"."z_tag_access" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_user_pk" ON "PNY_CONAGEN_DBO"."z_user" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_user_role_pk" ON "PNY_CONAGEN_DBO"."z_user_role" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_winston_pk" ON "PNY_CONAGEN_DBO"."z_winston" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."seq_blacklist_pk" ON "PNY_CONAGEN_DBO"."seq_blacklist" ("id") 
    ;
CREATE INDEX "PNY_CONAGEN_DBO"."seq_blacklist_user_id_idx" ON "PNY_CONAGEN_DBO"."seq_blacklist" ("user_id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."seq_feature_pk" ON "PNY_CONAGEN_DBO"."seq_feature" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."sequence_pk" ON "PNY_CONAGEN_DBO"."sequence" ("id") 
    ;
CREATE INDEX "PNY_CONAGEN_DBO"."sequence_user_id_idx" ON "PNY_CONAGEN_DBO"."sequence" ("user_id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."sequence_j5run_pk" ON "PNY_CONAGEN_DBO"."sequence_j5run" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."strain_pk" ON "PNY_CONAGEN_DBO"."strain" ("id") 
    ;
CREATE INDEX "PNY_CONAGEN_DBO"."strain_user_id_idx" ON "PNY_CONAGEN_DBO"."strain" ("user_id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."strain_plasmid_pk" ON "PNY_CONAGEN_DBO"."strain_plasmid" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."tag_pk" ON "PNY_CONAGEN_DBO"."tag" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."tag_access_pk" ON "PNY_CONAGEN_DBO"."tag_access" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."user_pk" ON "PNY_CONAGEN_DBO"."user" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."user_role_pk" ON "PNY_CONAGEN_DBO"."user_role" ("id") 
    ;
CREATE INDEX "PNY_CONAGEN_DBO"."user_role_user_id_idx" ON "PNY_CONAGEN_DBO"."user_role" ("user_id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_DE_bin_pk" ON "PNY_CONAGEN_DBO"."z_DE_bin" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_DE_bin_cell_pk" ON "PNY_CONAGEN_DBO"."z_DE_bin_cell" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_access_control_pk" ON "PNY_CONAGEN_DBO"."z_access_control" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_activity_log_pk" ON "PNY_CONAGEN_DBO"."z_activity_log" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."assembly_run_pk" ON "PNY_CONAGEN_DBO"."assembly_run" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."assembly_operation_pk" ON "PNY_CONAGEN_DBO"."assembly_operation" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."assembly_op_input_pk" ON "PNY_CONAGEN_DBO"."assembly_op_input" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."assembly_op_output_pk" ON "PNY_CONAGEN_DBO"."assembly_op_output" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_attached_design_ruleset_pk" ON "PNY_CONAGEN_DBO"."z_attached_design_ruleset" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_attached_tag_pk" ON "PNY_CONAGEN_DBO"."z_attached_tag" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_custom_field_pk" ON "PNY_CONAGEN_DBO"."z_custom_field" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_custom_field_value_pk" ON "PNY_CONAGEN_DBO"."z_custom_field_value" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_custom_j5parameters_pk" ON "PNY_CONAGEN_DBO"."z_custom_j5parameters" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_custom_setting_pk" ON "PNY_CONAGEN_DBO"."z_custom_setting" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_dd_part_pk" ON "PNY_CONAGEN_DBO"."z_dd_part" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_design_rule_pk" ON "PNY_CONAGEN_DBO"."z_design_rule" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_design_rule_tag_pk" ON "PNY_CONAGEN_DBO"."z_design_rule_tag" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_design_ruleset_pk" ON "PNY_CONAGEN_DBO"."z_design_ruleset" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."z_devicedesign_pk" ON "PNY_CONAGEN_DBO"."z_devicedesign" ("logId") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."attached_design_ruleset_pk" ON "PNY_CONAGEN_DBO"."attached_design_ruleset" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."attached_tag_pk" ON "PNY_CONAGEN_DBO"."attached_tag" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."clob_buffer_pk" ON "PNY_CONAGEN_DBO"."clob_buffer" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."custom_field_pk" ON "PNY_CONAGEN_DBO"."custom_field" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."custom_field_value_pk" ON "PNY_CONAGEN_DBO"."custom_field_value" ("id") 
    ;
CREATE INDEX "PNY_CONAGEN_DBO"."custom_j5parameter_user_id_idx" ON "PNY_CONAGEN_DBO"."custom_j5parameters" ("user_id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."custom_j5parameters_pk" ON "PNY_CONAGEN_DBO"."custom_j5parameters" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."custom_setting_pk" ON "PNY_CONAGEN_DBO"."custom_setting" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."dd_part_pk" ON "PNY_CONAGEN_DBO"."dd_part" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."design_rule_pk" ON "PNY_CONAGEN_DBO"."design_rule" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."design_rule_tag_pk" ON "PNY_CONAGEN_DBO"."design_rule_tag" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."design_ruleset_pk" ON "PNY_CONAGEN_DBO"."design_ruleset" ("id") 
    ;
CREATE INDEX "PNY_CONAGEN_DBO"."devicedesign_user_id_idx" ON "PNY_CONAGEN_DBO"."devicedesign" ("user_id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."devicedesign_pk" ON "PNY_CONAGEN_DBO"."devicedesign" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."eugene_rule_pk" ON "PNY_CONAGEN_DBO"."eugene_rule" ("id") 
    ;
CREATE INDEX "PNY_CONAGEN_DBO"."group_user_id_idx" ON "PNY_CONAGEN_DBO"."group" ("user_id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."group_pk" ON "PNY_CONAGEN_DBO"."group" ("id") 
    ;
CREATE INDEX "PNY_CONAGEN_DBO"."group_user_user_id_idx" ON "PNY_CONAGEN_DBO"."group_user" ("user_id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."group_user_pk" ON "PNY_CONAGEN_DBO"."group_user" ("id") 
    ;
CREATE INDEX "PNY_CONAGEN_DBO"."j5run_user_id_idx" ON "PNY_CONAGEN_DBO"."j5run" ("user_id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."j5run_pk" ON "PNY_CONAGEN_DBO"."j5run" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."j5run_construct_pk" ON "PNY_CONAGEN_DBO"."j5run_construct" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."lock_pk" ON "PNY_CONAGEN_DBO"."lock" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."master_pk" ON "PNY_CONAGEN_DBO"."master" ("id") 
    ;
CREATE INDEX "PNY_CONAGEN_DBO"."part_user_id_idx" ON "PNY_CONAGEN_DBO"."part" ("user_id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."part_pk" ON "PNY_CONAGEN_DBO"."part" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."part_tag_pk" ON "PNY_CONAGEN_DBO"."part_tag" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."plate_pk" ON "PNY_CONAGEN_DBO"."plate" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."plate_set_pk" ON "PNY_CONAGEN_DBO"."plate_set" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."plate_well_pk" ON "PNY_CONAGEN_DBO"."plate_well" ("id") 
    ;
CREATE INDEX "PNY_CONAGEN_DBO"."preset_user_id_idx" ON "PNY_CONAGEN_DBO"."preset" ("user_id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."preset_pk" ON "PNY_CONAGEN_DBO"."preset" ("id") 
    ;
CREATE INDEX "PNY_CONAGEN_DBO"."project_user_id_idx" ON "PNY_CONAGEN_DBO"."project" ("user_id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."project_pk" ON "PNY_CONAGEN_DBO"."project" ("id") 
    ;
CREATE INDEX "PNY_CONAGEN_DBO"."protein_user_id_idx" ON "PNY_CONAGEN_DBO"."protein" ("user_id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."protein_pk" ON "PNY_CONAGEN_DBO"."protein" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."protein_feature_pk" ON "PNY_CONAGEN_DBO"."protein_feature" ("id") 
    ;
CREATE INDEX "PNY_CONAGEN_DBO"."protocol_user_id_idx" ON "PNY_CONAGEN_DBO"."protocol" ("user_id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."protocol_pk" ON "PNY_CONAGEN_DBO"."protocol" ("id") 
    ;
CREATE UNIQUE INDEX "PNY_CONAGEN_DBO"."role_pk" ON "PNY_CONAGEN_DBO"."role" ("id") 
    ;


----- Table Constraints ------
ALTER TABLE "PNY_CONAGEN_DBO"."role" ADD CONSTRAINT "role_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."protocol" ADD CONSTRAINT "protocol_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."protein_feature" ADD CONSTRAINT "protein_feature_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."protein" ADD CONSTRAINT "protein_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."project" ADD CONSTRAINT "project_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."preset" ADD CONSTRAINT "preset_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."plate_well" ADD CONSTRAINT "plate_well_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."plate_set" ADD CONSTRAINT "plate_set_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."plate" ADD CONSTRAINT "plate_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."part_tag" ADD CONSTRAINT "part_tag_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."part" ADD CONSTRAINT "part_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."master" ADD CONSTRAINT "master_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."lock" ADD CONSTRAINT "lock_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."j5run_construct" ADD CONSTRAINT "j5run_construct_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."j5run" ADD CONSTRAINT "j5run_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."group_user" ADD CONSTRAINT "group_user_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."group" ADD CONSTRAINT "group_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."eugene_rule" ADD CONSTRAINT "eugene_rule_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."devicedesign" ADD CONSTRAINT "devicedesign_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."design_ruleset" ADD CONSTRAINT "design_ruleset_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."design_rule_tag" ADD CONSTRAINT "design_rule_tag_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."design_rule" ADD CONSTRAINT "design_rule_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."dd_part" ADD CONSTRAINT "dd_part_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."custom_setting" ADD CONSTRAINT "custom_setting_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."custom_j5parameters" ADD CONSTRAINT "custom_j5parameters_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."custom_field_value" ADD CONSTRAINT "custom_field_value_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."custom_field" ADD CONSTRAINT "custom_field_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."clob_buffer" ADD CONSTRAINT "clob_buffer_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."attached_tag" ADD CONSTRAINT "attached_tag_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."attached_design_ruleset" ADD CONSTRAINT "attached_design_ruleset_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_devicedesign" ADD CONSTRAINT "z_devicedesign_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_design_ruleset" ADD CONSTRAINT "z_design_ruleset_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_design_rule_tag" ADD CONSTRAINT "z_design_rule_tag_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_design_rule" ADD CONSTRAINT "z_design_rule_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_dd_part" ADD CONSTRAINT "z_dd_part_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_custom_setting" ADD CONSTRAINT "z_custom_setting_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_custom_j5parameters" ADD CONSTRAINT "z_custom_j5parameters_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_custom_field_value" ADD CONSTRAINT "z_custom_field_value_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_custom_field" ADD CONSTRAINT "z_custom_field_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_attached_tag" ADD CONSTRAINT "z_attached_tag_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_attached_design_ruleset" ADD CONSTRAINT "z_attached_design_ruleset_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_activity_log" ADD CONSTRAINT "z_activity_log_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_access_control" ADD CONSTRAINT "z_access_control_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_DE_bin_cell" ADD CONSTRAINT "z_DE_bin_cell_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_DE_bin" ADD CONSTRAINT "z_DE_bin_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."user_role" ADD CONSTRAINT "user_role_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."user" ADD CONSTRAINT "user_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."tag_access" ADD CONSTRAINT "tag_access_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."tag" ADD CONSTRAINT "tag_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."strain_plasmid" ADD CONSTRAINT "strain_plasmid_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."strain" ADD CONSTRAINT "strain_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."sequence_j5run" ADD CONSTRAINT "sequence_j5run_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."sequence" ADD CONSTRAINT "sequence_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."seq_feature" ADD CONSTRAINT "seq_feature_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."seq_blacklist" ADD CONSTRAINT "seq_blacklist_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_winston" ADD CONSTRAINT "z_winston_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_user_role" ADD CONSTRAINT "z_user_role_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_user" ADD CONSTRAINT "z_user_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_tag_access" ADD CONSTRAINT "z_tag_access_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_tag" ADD CONSTRAINT "z_tag_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_strain_plasmid" ADD CONSTRAINT "z_strain_plasmid_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_strain" ADD CONSTRAINT "z_strain_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_sequence_j5run" ADD CONSTRAINT "z_sequence_j5run_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_sequence" ADD CONSTRAINT "z_sequence_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_seq_feature" ADD CONSTRAINT "z_seq_feature_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_seq_blacklist" ADD CONSTRAINT "z_seq_blacklist_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_role" ADD CONSTRAINT "z_role_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_protocol" ADD CONSTRAINT "z_protocol_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_protein_feature" ADD CONSTRAINT "z_protein_feature_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_protein" ADD CONSTRAINT "z_protein_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_project" ADD CONSTRAINT "z_project_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_preset" ADD CONSTRAINT "z_preset_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_plate_well" ADD CONSTRAINT "z_plate_well_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_plate_set" ADD CONSTRAINT "z_plate_set_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_plate" ADD CONSTRAINT "z_plate_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_part_tag" ADD CONSTRAINT "z_part_tag_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_part" ADD CONSTRAINT "z_part_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_master" ADD CONSTRAINT "z_master_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_lock" ADD CONSTRAINT "z_lock_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_j5run_construct" ADD CONSTRAINT "z_j5run_construct_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_j5run" ADD CONSTRAINT "z_j5run_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_group_user" ADD CONSTRAINT "z_group_user_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_group" ADD CONSTRAINT "z_group_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_eugene_rule" ADD CONSTRAINT "z_eugene_rule_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."access_control" ADD CONSTRAINT "access_control_pk" PRIMARY KEY ("acId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."DE_bin_cell" ADD CONSTRAINT "DE_bin_cell_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."DE_bin" ADD CONSTRAINT "DE_bin_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."assembly_op_input" ADD CONSTRAINT "assembly_op_input_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."assembly_op_output" ADD CONSTRAINT "assembly_op_output_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."assembly_operation" ADD CONSTRAINT "assembly_operation_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."assembly_run" ADD CONSTRAINT "assembly_run_pk" PRIMARY KEY ("id")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_assembly_op_input" ADD CONSTRAINT "z_assembly_op_input_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_assembly_op_output" ADD CONSTRAINT "z_assembly_op_output_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_assembly_operation" ADD CONSTRAINT "z_assembly_operation_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_assembly_run" ADD CONSTRAINT "z_assembly_run_pk" PRIMARY KEY ("logId")
  USING INDEX  ENABLE;


----- Table Ref Constraints ------
ALTER TABLE "PNY_CONAGEN_DBO"."access_control" ADD CONSTRAINT "access_control_dependsOn_fk" FOREIGN KEY ("dependsOn")
	  REFERENCES "PNY_CONAGEN_DBO"."access_control" ("acId") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."DE_bin_cell" ADD CONSTRAINT "DE_bin_cell_de_bin_fk" FOREIGN KEY ("de_bin_id")
	  REFERENCES "PNY_CONAGEN_DBO"."DE_bin" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."access_control" ADD CONSTRAINT "access_control_user_fk" FOREIGN KEY ("userId")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."custom_field" ADD CONSTRAINT "custom_field_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."custom_j5parameters" ADD CONSTRAINT "custom_j5parameters_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."devicedesign" ADD CONSTRAINT "devicedesign_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."group" ADD CONSTRAINT "group_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."group_user" ADD CONSTRAINT "group_user_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."j5run" ADD CONSTRAINT "j5run_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."lock" ADD CONSTRAINT "lock_locked_by_fk" FOREIGN KEY ("locked_by")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."part" ADD CONSTRAINT "part_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."part_tag" ADD CONSTRAINT "part_tag_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."plate" ADD CONSTRAINT "plate_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."plate_set" ADD CONSTRAINT "plate_set_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."plate_well" ADD CONSTRAINT "plate_well_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."preset" ADD CONSTRAINT "preset_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."project" ADD CONSTRAINT "project_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."protein" ADD CONSTRAINT "protein_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."protocol" ADD CONSTRAINT "protocol_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."seq_blacklist" ADD CONSTRAINT "seq_blacklist_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."sequence" ADD CONSTRAINT "sequence_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."strain" ADD CONSTRAINT "strain_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."tag_access" ADD CONSTRAINT "tag_access_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."user_role" ADD CONSTRAINT "user_role_user_fk" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."z_activity_log" ADD CONSTRAINT "z_activity_log_fk_user_id" FOREIGN KEY ("user_id")
	  REFERENCES "PNY_CONAGEN_DBO"."user" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."design_rule_tag" ADD CONSTRAINT "design_rule_tag_tag_fk" FOREIGN KEY ("tag_id")
	  REFERENCES "PNY_CONAGEN_DBO"."tag" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."part_tag" ADD CONSTRAINT "part_tag_tag_fk" FOREIGN KEY ("tag_id")
	  REFERENCES "PNY_CONAGEN_DBO"."tag" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."tag_access" ADD CONSTRAINT "tag_access_tag_fk" FOREIGN KEY ("tag_id")
	  REFERENCES "PNY_CONAGEN_DBO"."tag" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."strain_plasmid" ADD CONSTRAINT "strain_plasmid_strain_fk" FOREIGN KEY ("strain_id")
	  REFERENCES "PNY_CONAGEN_DBO"."strain" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."part" ADD CONSTRAINT "part_sequence_fk" FOREIGN KEY ("sequence_id")
	  REFERENCES "PNY_CONAGEN_DBO"."sequence" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."seq_blacklist" ADD CONSTRAINT "seq_blacklist_sequence_fk" FOREIGN KEY ("sequence_id")
	  REFERENCES "PNY_CONAGEN_DBO"."sequence" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."seq_feature" ADD CONSTRAINT "seq_feature_sequence_fk" FOREIGN KEY ("sequence_id")
	  REFERENCES "PNY_CONAGEN_DBO"."sequence" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."sequence_j5run" ADD CONSTRAINT "sequence_j5run_sequence_fk" FOREIGN KEY ("sequence_id")
	  REFERENCES "PNY_CONAGEN_DBO"."sequence" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."strain_plasmid" ADD CONSTRAINT "strain_plasmid_sequence_fk" FOREIGN KEY ("sequence_id")
	  REFERENCES "PNY_CONAGEN_DBO"."sequence" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."user_role" ADD CONSTRAINT "user_role_role_fk" FOREIGN KEY ("role_id")
	  REFERENCES "PNY_CONAGEN_DBO"."role" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."protein_feature" ADD CONSTRAINT "protein_feature_protein_fk" FOREIGN KEY ("protein_id")
	  REFERENCES "PNY_CONAGEN_DBO"."protein" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."seq_feature" ADD CONSTRAINT "seq_feature_protein_fk" FOREIGN KEY ("protein_id")
	  REFERENCES "PNY_CONAGEN_DBO"."protein" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."devicedesign" ADD CONSTRAINT "devicedesign_project_fk" FOREIGN KEY ("project_id")
	  REFERENCES "PNY_CONAGEN_DBO"."project" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."j5run" ADD CONSTRAINT "j5run_preset_fk" FOREIGN KEY ("preset_id")
	  REFERENCES "PNY_CONAGEN_DBO"."preset" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."plate" ADD CONSTRAINT "plate_plate_set_fk" FOREIGN KEY ("plate_set_id")
	  REFERENCES "PNY_CONAGEN_DBO"."plate_set" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."assembly_op_input" ADD CONSTRAINT "assembly_op_input_plate_set_fk" FOREIGN KEY ("plate_set_id")
	  REFERENCES "PNY_CONAGEN_DBO"."plate_set" ("id") ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."plate_well" ADD CONSTRAINT "plate_well_plate_fk" FOREIGN KEY ("plate_id")
	  REFERENCES "PNY_CONAGEN_DBO"."plate" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."dd_part" ADD CONSTRAINT "dd_part_part_fk" FOREIGN KEY ("part_id")
	  REFERENCES "PNY_CONAGEN_DBO"."part" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."part_tag" ADD CONSTRAINT "part_tag_part_fk" FOREIGN KEY ("part_id")
	  REFERENCES "PNY_CONAGEN_DBO"."part" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."sequence_j5run" ADD CONSTRAINT "sequence_j5run_j5run_fk" FOREIGN KEY ("j5run_id")
	  REFERENCES "PNY_CONAGEN_DBO"."j5run" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."j5run_construct" ADD CONSTRAINT "j5run_construct_j5run_fk" FOREIGN KEY ("j5run_id")
	  REFERENCES "PNY_CONAGEN_DBO"."j5run" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."assembly_run" ADD CONSTRAINT "assembly_run_j5run_fk" FOREIGN KEY ("j5run_id")
	  REFERENCES "PNY_CONAGEN_DBO"."j5run" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."access_control" ADD CONSTRAINT "access_control_group_fk" FOREIGN KEY ("groupId")
	  REFERENCES "PNY_CONAGEN_DBO"."group" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."group_user" ADD CONSTRAINT "group_user_group_fk" FOREIGN KEY ("group_id")
	  REFERENCES "PNY_CONAGEN_DBO"."group" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."tag_access" ADD CONSTRAINT "tag_access_group_fk" FOREIGN KEY ("group_id")
	  REFERENCES "PNY_CONAGEN_DBO"."group" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."DE_bin" ADD CONSTRAINT "DE_bin_devicedesign_fk" FOREIGN KEY ("devicedesign_id")
	  REFERENCES "PNY_CONAGEN_DBO"."devicedesign" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."attached_design_ruleset" ADD CONSTRAINT "attached_desi_devicedesign_fk" FOREIGN KEY ("devicedesign_id")
	  REFERENCES "PNY_CONAGEN_DBO"."devicedesign" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."dd_part" ADD CONSTRAINT "dd_part_devicedesign_fk" FOREIGN KEY ("devicedesign_id")
	  REFERENCES "PNY_CONAGEN_DBO"."devicedesign" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."eugene_rule" ADD CONSTRAINT "eugene_rule_devicedesign_fk" FOREIGN KEY ("devicedesign_id")
	  REFERENCES "PNY_CONAGEN_DBO"."devicedesign" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."j5run" ADD CONSTRAINT "j5run_devicedesign_fk" FOREIGN KEY ("devicedesign_id")
	  REFERENCES "PNY_CONAGEN_DBO"."devicedesign" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."attached_design_ruleset" ADD CONSTRAINT "attached_desi_design_rulese_fk" FOREIGN KEY ("design_ruleset_id")
	  REFERENCES "PNY_CONAGEN_DBO"."design_ruleset" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."design_rule" ADD CONSTRAINT "design_rule_design_ruleset_fk" FOREIGN KEY ("design_ruleset_id")
	  REFERENCES "PNY_CONAGEN_DBO"."design_ruleset" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."design_rule_tag" ADD CONSTRAINT "design_rule_tag_design_rule_fk" FOREIGN KEY ("design_rule_id")
	  REFERENCES "PNY_CONAGEN_DBO"."design_rule" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."custom_field_value" ADD CONSTRAINT "custom_field_custom_field_fk" FOREIGN KEY ("custom_field_id")
	  REFERENCES "PNY_CONAGEN_DBO"."custom_field" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."assembly_operation" ADD CONSTRAINT "assembly_oper_assembly_run_fk" FOREIGN KEY ("assembly_run_id")
	  REFERENCES "PNY_CONAGEN_DBO"."assembly_run" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."assembly_op_input" ADD CONSTRAINT "assembly_op_i_assembly_oper_fk" FOREIGN KEY ("assembly_operation_id")
	  REFERENCES "PNY_CONAGEN_DBO"."assembly_operation" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."assembly_op_output" ADD CONSTRAINT "assembly_op_o_assembly_oper_fk" FOREIGN KEY ("assembly_operation_id")
	  REFERENCES "PNY_CONAGEN_DBO"."assembly_operation" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."plate_set" ADD CONSTRAINT "plate_set_assembly_oper_fk" FOREIGN KEY ("assembly_operation_id")
	  REFERENCES "PNY_CONAGEN_DBO"."assembly_operation" ("id") ON DELETE CASCADE ENABLE;
ALTER TABLE "PNY_CONAGEN_DBO"."assembly_op_input" ADD CONSTRAINT "assembly_op_i_assembly_op_o_fk" FOREIGN KEY ("assembly_op_output_id")
	  REFERENCES "PNY_CONAGEN_DBO"."assembly_op_output" ("id") ENABLE;


----- Functions ------
CREATE OR REPLACE EDITIONABLE FUNCTION "PNY_CONAGEN_DBO"."CONCAT_CLOB_BUFFER" 
(
  BUFFER_ID IN VARCHAR2 
) RETURN CLOB
IS
  accumulator CLOB;
  counter NUMBER := 0;
BEGIN
  FOR x IN 
    (SELECT "chunk" 
     FROM "clob_buffer"
     WHERE "bufferId" = BUFFER_ID
     ORDER BY "chunkIndex")
  LOOP
    accumulator := accumulator || x."chunk";  
  END LOOP;
  
  RETURN accumulator;
END CONCAT_CLOB_BUFFER;
/


------ Insert Initial Values --------

insert into "PNY_CONAGEN_DBO"."user" ("id","username","firstName","lastName") values (0, 'app','app','server');
Insert into "PNY_CONAGEN_DBO"."role" ("id","name","description") values (1,'editor','Can edit their own non-shared data');
Insert into "PNY_CONAGEN_DBO"."role" ("id","name","description") values (2,'admin','Full access to all app functionality.');
Insert into "PNY_CONAGEN_DBO"."role" ("id","name","description") values (3,'user_manager','Can manage users and assign roles.');
Insert into "PNY_CONAGEN_DBO"."role" ("id","name","description") values (4,'viewer','Can view data in the shared Peony repo');
Insert into "PNY_CONAGEN_DBO"."role" ("id","name","description") values (5,'contributor','Can add data into the shared Peony repo');
Insert into "PNY_CONAGEN_DBO"."role" ("id","name","description") values (6,'tag_admin','Can manage and assign permissions for tags.');
Insert into "PNY_CONAGEN_DBO"."user" ("id","username","firstName","lastName", "password", "activated", "activeFlag") values (1, 'admin','Admin','User', '$2a$10$a3BOTytYHBko.I4aKpAPR.4b6Sr3s93mUH.UNwMyDGhdxo42sm.GW', 1, 1);
insert into "PNY_CONAGEN_DBO"."user_role" ("user_id", "role_id") values (1, 2);
commit;

