CREATE SEQUENCE  "PEONY_OWNER"."design_rule_tag_seq"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOPARTITION ;

create or replace TRIGGER "design_rule_tag_trg" 
BEFORE INSERT ON "design_rule_tag" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."id" IS NULL THEN
      SELECT "design_rule_tag_seq".NEXTVAL INTO :NEW."id" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
