
ALTER SESSION SET CURRENT_SCHEMA = &&SCHEMA_OWNER_NAME;

EXECUTE DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'PRETTY',true);
EXECUTE DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SQLTERMINATOR',false);
EXECUTE DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'STORAGE',false);
EXECUTE DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SEGMENT_ATTRIBUTES',false);
EXECUTE DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'TABLESPACE',false);
EXECUTE DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'CONSTRAINTS',false);
EXECUTE DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'REF_CONSTRAINTS',false);
EXECUTE DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'CONSTRAINTS_AS_ALTER',false);
EXECUTE DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'OID',false);
EXECUTE DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SIZE_BYTE_KEYWORD',true);

DECLARE 
  logDetailColumns VARCHAR2(1000) :=  'CREATE TABLE "&SCHEMA_OWNER_NAME".\1' || chr(10) || '( ' || chr(10) ||
                                      ' "logId" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,' || chr(10) ||
                                      ' "logSessionId" VARCHAR2(50 BYTE),' || chr(10) ||
                                      ' "logAction" VARCHAR2(400 BYTE),' || chr(10) ||
                                      ' "dateLogged" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL,' || chr(10) ||
                                      ' "loggedBy" NUMBER,' || chr(10) ||
                                      '\3 TABLESPACE "&LOG_TABLESPACE_NAME"';
                                      
  logDetailSearch VARCHAR2(1000) :=   'CREATE TABLE\s+(".+")\s+(\()([^.]+)';                           
                                    
BEGIN

  FOR logTableSchema in (
    select  REGEXP_REPLACE(
                REPLACE(
                        REPLACE(DBMS_METADATA.GET_DDL('TABLE',TABLE_NAME,'&SCHEMA_OWNER_NAME'), 
                                                      'TABLE "&SCHEMA_OWNER_NAME"."' || TABLE_NAME || '" ', 
                                                      'TABLE "' || TABLE_NAME || '" '),
                       'TABLE "' || TABLE_NAME || '" ',  
                       'TABLE "z_' || TABLE_NAME || '" '),
                logDetailSearch, logDetailColumns,1,1) str,
                TABLE_NAME
    from all_tables 
    where TABLE_NAME not like 'z_%' 
    and TABLE_NAME not in ('import_log','clob_buffer')
    and owner = '&SCHEMA_OWNER_NAME'
    order by table_name
  )
  LOOP
    EXECUTE IMMEDIATE ('' || logTableSchema.str);
  END LOOP;


END;
/

EXECUTE DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'DEFAULT');
