--DEFINE the following at the top of your schemaConfig script or pass it in as a parameter 
--DEFINE SCHEMA_CODE = 'TESELAGEN';

--Removed this so you can run from schemaConfig.sql
--@@schemaConfig.sql;

COLUMN C1 NEW_VAL SCHEMA_OWNER_NAME;
SELECT 'PNY_' || '&SCHEMA_CODE' || '_DBO' C1 FROM DUAL;

COLUMN C2 NEW_VAL APP_USER;
SELECT 'PNY_' || '&SCHEMA_CODE' || '_APP' C2 FROM DUAL;

COLUMN C3 NEW_VAL APP_ROLE;
SELECT 'PNY_' || '&SCHEMA_CODE' || '_AR' C3 FROM DUAL;

COLUMN C4 NEW_VAL SCHEMA_OWNER_PASSWORD;
SELECT DBMS_RANDOM.STRING('X', 2) ||
       DBMS_RANDOM.STRING('A', 4) || 
       DBMS_RANDOM.STRING('X', 2) || 
       DBMS_RANDOM.STRING('A', 1) || 
       DBMS_RANDOM.STRING('X', 5) || 
       DBMS_RANDOM.STRING('A', 3) C4 FROM DUAL;
       
COLUMN C5 NEW_VAL APP_USER_PASSWORD;
SELECT DBMS_RANDOM.STRING('X', 2) ||
       DBMS_RANDOM.STRING('A', 4) || 
       DBMS_RANDOM.STRING('X', 2) || 
       DBMS_RANDOM.STRING('A', 1) || 
       DBMS_RANDOM.STRING('X', 5) || 
       DBMS_RANDOM.STRING('A', 3) C5 FROM DUAL;
       

COLUMN C6 NEW_VAL TABLESPACE_NAME;
SELECT 'PNY_' || '&SCHEMA_CODE' || '_DATA' C6 FROM DUAL;

COLUMN C7 NEW_VAL TABLESPACE_FILE_NAME;
SELECT 'PNY_' || '&SCHEMA_CODE' || '_DATA.dat' C7 FROM DUAL;

COLUMN C8 NEW_VAL TEMP_TABLESPACE_NAME;
SELECT 'PNY_' || '&SCHEMA_CODE' || '_TMP' C8 FROM DUAL;

COLUMN C9 NEW_VAL TEMP_TABLESPACE_FILE_NAME;
SELECT 'PNY_' || '&SCHEMA_CODE' || '_TMP.dat' C9 FROM DUAL;

COLUMN C10 NEW_VAL LOG_TABLESPACE_NAME;
SELECT 'PNY_' || '&SCHEMA_CODE' || '_LOG' C10 FROM DUAL;

COLUMN C11 NEW_VAL LOG_TABLESPACE_FILE_NAME;
SELECT 'PNY_' || '&SCHEMA_CODE' || '_LOG.dat' C11 FROM DUAL;

COLUMN C12 NEW_VAL PROVISION_TABLESPACE;
SELECT DECODE(&AWS_RDS, 1, 'provisionManagedTablespaces', 'provisionLocalTablespaces') C12 FROM DUAL;
--SELECT DECODE(&AWS_RDS, 1, 'testInclude.sql', 'provisionLocalTablespaces') C12 FROM DUAL;

DEFINE SCHEMA_OWNER_NAME;
DEFINE APP_USER;
DEFINE APP_ROLE;
DEFINE SCHEMA_OWNER_PASSWORD;
DEFINE APP_USER_PASSWORD;
DEFINE TABLESPACE_NAME;
DEFINE TABLESPACE_FILE_NAME;
DEFINE TEMP_TABLESPACE_NAME;
DEFINE TEMP_TABLESPACE_FILE_NAME;
DEFINE LOG_TABLESPACE_NAME;
DEFINE LOG_TABLESPACE_FILE_NAME;
DEFINE PROVISION_TABLESPACE;

--@@&&PROVISION_TABLESPACE;
