set linesize 1000;

select 
  dd.utc.extract('/ROWSET/ROW/TABLE_NAME/text()') TABLE_NAME, 
  dd.utc.extract('/ROWSET/ROW/COLUMN_NAME/text()') COLUMN_NAME,
  dd.utc.extract('/ROWSET/ROW/DATA_DEFAULT/text()') DATA_DEFAULT
from 
  (select 
      dbms_xmlgen.getxmltype('select TABLE_NAME, COLUMN_NAME, DATA_DEFAULT from user_tab_cols') utc
  from dual) dd;

select 
  TABLE_NAME, COLUMN_NAME, REPLACE(DATA_DEFAULT, '"' || sys_context( 'userenv', 'current_schema' ) || '".', '' ) DATA_DEFAULT 
from 
  (select 
      dbms_xmlgen.getxmltype('select TABLE_NAME, COLUMN_NAME, DATA_DEFAULT from user_tab_cols where user_generated = ''YES''') utc
  from dual) dd,
  XMLTABLE('/ROWSET/ROW' PASSING dd.utc COLUMNS "TABLE_NAME" VARCHAR2(30) PATH 'TABLE_NAME', "COLUMN_NAME" VARCHAR2(30) PATH 'COLUMN_NAME', "DATA_DEFAULT" VARCHAR2(4000) PATH 'DATA_DEFAULT');



<ROWSET>
 <ROW>
  <TABLE_NAME>DE_bin</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin</TABLE_NAME>
  <COLUMN_NAME>DEIndex</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin</TABLE_NAME>
  <COLUMN_NAME>devicedesign_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin</TABLE_NAME>
  <COLUMN_NAME>iconID</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin</TABLE_NAME>
  <COLUMN_NAME>binName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin</TABLE_NAME>
  <COLUMN_NAME>extra3PrimeBps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin</TABLE_NAME>
  <COLUMN_NAME>extra5PrimeBps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin</TABLE_NAME>
  <COLUMN_NAME>fro</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin</TABLE_NAME>
  <COLUMN_NAME>dsf</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin</TABLE_NAME>
  <COLUMN_NAME>directionForward</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_DE_bin"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>part_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>de_bin_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>fas</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>index</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_DE_bin_cell"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>access_control</TABLE_NAME>
  <COLUMN_NAME>userId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>access_control</TABLE_NAME>
  <COLUMN_NAME>objectName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>access_control</TABLE_NAME>
  <COLUMN_NAME>objectId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>access_control</TABLE_NAME>
  <COLUMN_NAME>acId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_access_control"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>access_control</TABLE_NAME>
  <COLUMN_NAME>dependsOn</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>access_control</TABLE_NAME>
  <COLUMN_NAME>creatorId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>access_control</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>access_control</TABLE_NAME>
  <COLUMN_NAME>groupId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>attached_tag</TABLE_NAME>
  <COLUMN_NAME>filterLogic</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>attached_tag</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>attached_tag</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>attached_tag</TABLE_NAME>
  <COLUMN_NAME>tagged_data_type</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>attached_tag</TABLE_NAME>
  <COLUMN_NAME>tag_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>attached_tag</TABLE_NAME>
  <COLUMN_NAME>tagged_data_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>attached_tag</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_attached_tag"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>clob_buffer</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>clob_buffer</TABLE_NAME>
  <COLUMN_NAME>chunkIndex</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>clob_buffer</TABLE_NAME>
  <COLUMN_NAME>bufferId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>clob_buffer</TABLE_NAME>
  <COLUMN_NAME>chunk</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>clob_buffer</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_clob_buffer"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_fields</TABLE_NAME>
  <COLUMN_NAME>fieldDataType</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_fields</TABLE_NAME>
  <COLUMN_NAME>fieldValue</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_fields</TABLE_NAME>
  <COLUMN_NAME>fieldName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_fields</TABLE_NAME>
  <COLUMN_NAME>objectName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_fields</TABLE_NAME>
  <COLUMN_NAME>objectId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_fields</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_custom_fields"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>mispriming_oligo_conc</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>output_seq_format</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>hmlgy_min_length_bps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>hmlgy_max_fraction_mismatches</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>suppress_pure_primers</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>suppress_primer_annotations</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_custom_j5parameters"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>master_oligo_num_of_digits</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>master_plasmid_num_of_digits</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>gibson_overlap_bps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>gibson_overlap_min_tm</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>gibson_overlap_max_tm</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>max_oligo_length_bps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>min_fragment_size_gibson_bps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>ggate_overhang_bps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>ggate_recognition_seq</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>ggate_termini_extra_seq</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>max_ids_ggate_overhangs_cmptbl</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>oligo_synthesis_cost_per_bp</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>oligo_page_pur_cost_per_piece</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>oligo_max_len_no_page_pur_bps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>min_pcr_product_bps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>dir_synth_cost_per_bp</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>dir_synth_min_cost_per_piece</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_gc_clamp</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_min_size</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_max_size</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_min_tm</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_max_tm</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_max_diff_tm</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_max_self_any_th</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_max_self_end_th</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_pair_max_compl_any_th</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_pair_max_compl_end_th</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_tm_santalucia</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_salt_corrections</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_dna_conc</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>mispriming_3pbp_to_warn_if_hit</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>mispriming_min_tm</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>mispriming_salt_conc</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>dd_part</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>dd_part</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>dd_part</TABLE_NAME>
  <COLUMN_NAME>part_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>dd_part</TABLE_NAME>
  <COLUMN_NAME>devicedesign_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>dd_part</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_dd_part"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>devicedesign</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>devicedesign</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>devicedesign</TABLE_NAME>
  <COLUMN_NAME>project_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>devicedesign</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>devicedesign</TABLE_NAME>
  <COLUMN_NAME>isCircular</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>devicedesign</TABLE_NAME>
  <COLUMN_NAME>combinatorial</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>devicedesign</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>devicedesign</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_devicedesign"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>eugene_rule</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>eugene_rule</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>eugene_rule</TABLE_NAME>
  <COLUMN_NAME>devicedesign_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>eugene_rule</TABLE_NAME>
  <COLUMN_NAME>compositionalOperator</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>eugene_rule</TABLE_NAME>
  <COLUMN_NAME>operand2Number</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>eugene_rule</TABLE_NAME>
  <COLUMN_NAME>operand2IsNumber</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>eugene_rule</TABLE_NAME>
  <COLUMN_NAME>negationOperator</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>eugene_rule</TABLE_NAME>
  <COLUMN_NAME>originalRuleLine</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>eugene_rule</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>eugene_rule</TABLE_NAME>
  <COLUMN_NAME>operand2_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>eugene_rule</TABLE_NAME>
  <COLUMN_NAME>operand1_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>eugene_rule</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_eugene_rule"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>group</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>group</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>group</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>group</TABLE_NAME>
  <COLUMN_NAME>description</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>group</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>group</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_group"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>group_user</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>group_user</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>group_user</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>group_user</TABLE_NAME>
  <COLUMN_NAME>group_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>group_user</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_group_user"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>j5run</TABLE_NAME>
  <COLUMN_NAME>clientTimeDiff</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>j5run</TABLE_NAME>
  <COLUMN_NAME>project_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>j5run</TABLE_NAME>
  <COLUMN_NAME>j5output</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>j5run</TABLE_NAME>
  <COLUMN_NAME>results</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>j5run</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>j5run</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>j5run</TABLE_NAME>
  <COLUMN_NAME>protocol_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>j5run</TABLE_NAME>
  <COLUMN_NAME>devicedesign_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>j5run</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>j5run</TABLE_NAME>
  <COLUMN_NAME>status</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>j5run</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>j5run</TABLE_NAME>
  <COLUMN_NAME>endDate</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>j5run</TABLE_NAME>
  <COLUMN_NAME>devicedesign_name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>j5run</TABLE_NAME>
  <COLUMN_NAME>date</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>j5run</TABLE_NAME>
  <COLUMN_NAME>assemblyType</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>j5run</TABLE_NAME>
  <COLUMN_NAME>assemblyMethod</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>j5run</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_j5run"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>master</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_master"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>master</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>master</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>master</TABLE_NAME>
  <COLUMN_NAME>masterPlasmidList</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>master</TABLE_NAME>
  <COLUMN_NAME>masterOligoList</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>master</TABLE_NAME>
  <COLUMN_NAME>masterDirectSynthesesList</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>master</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>preferred5PrimeOverhangs</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>preferred3PrimeOverhangs</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>partSource</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>sequence_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>size</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>iconID</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>features</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>directionForward</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>revComp</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>endBP</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>genbankStartBP</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>FQDN</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>definitionHash</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>part</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_part"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>preset</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>preset</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>preset</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>preset</TABLE_NAME>
  <COLUMN_NAME>j5parameters</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>preset</TABLE_NAME>
  <COLUMN_NAME>presetName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>preset</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_preset"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>project</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>project</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>project</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>project</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>project</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_project"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>protein</TABLE_NAME>
  <COLUMN_NAME>shared_repo</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein</TABLE_NAME>
  <COLUMN_NAME>sequence</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein</TABLE_NAME>
  <COLUMN_NAME>size</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein</TABLE_NAME>
  <COLUMN_NAME>description</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein</TABLE_NAME>
  <COLUMN_NAME>circular</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein</TABLE_NAME>
  <COLUMN_NAME>hash</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein</TABLE_NAME>
  <COLUMN_NAME>FQDN</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_protein"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>protein_feature</TABLE_NAME>
  <COLUMN_NAME>prot_feature_type_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein_feature</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein_feature</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein_feature</TABLE_NAME>
  <COLUMN_NAME>protein_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein_feature</TABLE_NAME>
  <COLUMN_NAME>notes</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein_feature</TABLE_NAME>
  <COLUMN_NAME>end</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein_feature</TABLE_NAME>
  <COLUMN_NAME>start</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein_feature</TABLE_NAME>
  <COLUMN_NAME>type</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein_feature</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protein_feature</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_protein_feature"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>protocol</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protocol</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protocol</TABLE_NAME>
  <COLUMN_NAME>contact</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protocol</TABLE_NAME>
  <COLUMN_NAME>version</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protocol</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protocol</TABLE_NAME>
  <COLUMN_NAME>assemblyMethods</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protocol</TABLE_NAME>
  <COLUMN_NAME>htmlContent</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protocol</TABLE_NAME>
  <COLUMN_NAME>author</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protocol</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>protocol</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_protocol"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>role</TABLE_NAME>
  <COLUMN_NAME>description</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>role</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>role</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_role"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>seq_blacklist</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>seq_blacklist</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>seq_blacklist</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_seq_blacklist"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>seq_blacklist</TABLE_NAME>
  <COLUMN_NAME>sequence_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>seq_blacklist</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>seq_feature</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>seq_feature</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>seq_feature</TABLE_NAME>
  <COLUMN_NAME>protein_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>seq_feature</TABLE_NAME>
  <COLUMN_NAME>notes</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>seq_feature</TABLE_NAME>
  <COLUMN_NAME>strand</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>seq_feature</TABLE_NAME>
  <COLUMN_NAME>sequence_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>seq_feature</TABLE_NAME>
  <COLUMN_NAME>end</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>seq_feature</TABLE_NAME>
  <COLUMN_NAME>start</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>seq_feature</TABLE_NAME>
  <COLUMN_NAME>type</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>seq_feature</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>seq_feature</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_seq_feature"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>sequence</TABLE_NAME>
  <COLUMN_NAME>molecule_type</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>sequence</TABLE_NAME>
  <COLUMN_NAME>type</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>sequence</TABLE_NAME>
  <COLUMN_NAME>shared_repo</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>sequence</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>sequence</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>sequence</TABLE_NAME>
  <COLUMN_NAME>sequence</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>sequence</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>sequence</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>sequence</TABLE_NAME>
  <COLUMN_NAME>size</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>sequence</TABLE_NAME>
  <COLUMN_NAME>description</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>sequence</TABLE_NAME>
  <COLUMN_NAME>circular</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>sequence</TABLE_NAME>
  <COLUMN_NAME>hash</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>sequence</TABLE_NAME>
  <COLUMN_NAME>FQDN</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>sequence</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_sequence"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>alias</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>creator</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>creatorEmail</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>fundingSource</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>status</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>bioSafetyLevel</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>parentStrain</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>links</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>genotype</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>keywords</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>summary</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>references</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>intellectualProperty</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>principalInvestigator</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>selectionMarkers</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>FQDN</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_strain"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>strain_plasmid</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain_plasmid</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain_plasmid</TABLE_NAME>
  <COLUMN_NAME>sequence_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain_plasmid</TABLE_NAME>
  <COLUMN_NAME>strain_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>strain_plasmid</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_strain_plasmid"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>tag</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_tag"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>tag</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>tag</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>tag</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>tag</TABLE_NAME>
  <COLUMN_NAME>color</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>tag</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>userRestrictionEnzymeGroups</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>userAccount</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>phoneNumber</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>activeFlag</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>middleName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>token</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>activated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>verifiedEmail</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>debugAccess</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>lastAccess</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>groupType</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>groupName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>activationCode</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>email</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>lastName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>firstName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>password</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>username</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_user"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>user_role</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user_role</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user_role</TABLE_NAME>
  <COLUMN_NAME>role_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user_role</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>user_role</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."s_user_role"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin</TABLE_NAME>
  <COLUMN_NAME>DEIndex</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin</TABLE_NAME>
  <COLUMN_NAME>devicedesign_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin</TABLE_NAME>
  <COLUMN_NAME>iconID</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin</TABLE_NAME>
  <COLUMN_NAME>binName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin</TABLE_NAME>
  <COLUMN_NAME>extra3PrimeBps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin</TABLE_NAME>
  <COLUMN_NAME>extra5PrimeBps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin</TABLE_NAME>
  <COLUMN_NAME>fro</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin</TABLE_NAME>
  <COLUMN_NAME>dsf</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin</TABLE_NAME>
  <COLUMN_NAME>directionForward</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_DE_bin"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>part_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>de_bin_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>fas</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>index</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_DE_bin_cell</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_DE_bin_cell"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_access_control</TABLE_NAME>
  <COLUMN_NAME>dependsOn</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_access_control</TABLE_NAME>
  <COLUMN_NAME>creatorId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_access_control</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_access_control</TABLE_NAME>
  <COLUMN_NAME>groupId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_access_control</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_access_control</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_access_control</TABLE_NAME>
  <COLUMN_NAME>userId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_access_control</TABLE_NAME>
  <COLUMN_NAME>objectName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_access_control</TABLE_NAME>
  <COLUMN_NAME>objectId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_access_control</TABLE_NAME>
  <COLUMN_NAME>acId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_access_control</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_access_control</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_access_control"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_activity_log</TABLE_NAME>
  <COLUMN_NAME>rawQuery</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_activity_log</TABLE_NAME>
  <COLUMN_NAME>recordsFetched</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_activity_log</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_activity_log</TABLE_NAME>
  <COLUMN_NAME>description</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_activity_log</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_activity_log</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_activity_log</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_activity_log</TABLE_NAME>
  <COLUMN_NAME>objectId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_activity_log</TABLE_NAME>
  <COLUMN_NAME>objectName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_activity_log</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_activity_log"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_attached_tag</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_attached_tag</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_attached_tag"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_attached_tag</TABLE_NAME>
  <COLUMN_NAME>filterLogic</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_attached_tag</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_attached_tag</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_attached_tag</TABLE_NAME>
  <COLUMN_NAME>tagged_data_type</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_attached_tag</TABLE_NAME>
  <COLUMN_NAME>tag_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_attached_tag</TABLE_NAME>
  <COLUMN_NAME>tagged_data_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_attached_tag</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_attached_tag</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_attached_tag</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_fields</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_fields</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_fields</TABLE_NAME>
  <COLUMN_NAME>fieldDataType</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_fields</TABLE_NAME>
  <COLUMN_NAME>fieldValue</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_fields</TABLE_NAME>
  <COLUMN_NAME>fieldName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_fields</TABLE_NAME>
  <COLUMN_NAME>objectName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_fields</TABLE_NAME>
  <COLUMN_NAME>objectId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_fields</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_fields</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_fields</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_custom_fields"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>master_oligo_num_of_digits</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>master_plasmid_num_of_digits</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>gibson_overlap_bps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>gibson_overlap_min_tm</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>gibson_overlap_max_tm</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>max_oligo_length_bps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>min_fragment_size_gibson_bps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>ggate_overhang_bps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>ggate_recognition_seq</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>ggate_termini_extra_seq</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>max_ids_ggate_overhangs_cmptbl</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>oligo_synthesis_cost_per_bp</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>oligo_page_pur_cost_per_piece</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>oligo_max_len_no_page_pur_bps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>min_pcr_product_bps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>dir_synth_cost_per_bp</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>dir_synth_min_cost_per_piece</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_gc_clamp</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_min_size</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_max_size</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_min_tm</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_max_tm</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_max_diff_tm</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_max_self_any_th</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_max_self_end_th</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_pair_max_compl_any_th</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_pair_max_compl_end_th</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_tm_santalucia</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_salt_corrections</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>primer_dna_conc</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>mispriming_3pbp_to_warn_if_hit</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>mispriming_min_tm</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>mispriming_salt_conc</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>mispriming_oligo_conc</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>output_seq_format</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>hmlgy_min_length_bps</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>hmlgy_max_fraction_mismatches</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>suppress_pure_primers</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>suppress_primer_annotations</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_custom_j5parameters</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_custom_j5parameters"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_dd_part</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_dd_part</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_dd_part</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_dd_part</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_dd_part</TABLE_NAME>
  <COLUMN_NAME>part_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_dd_part</TABLE_NAME>
  <COLUMN_NAME>devicedesign_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_dd_part</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_dd_part</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_dd_part</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_dd_part"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_devicedesign</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_devicedesign</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_devicedesign</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_devicedesign</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_devicedesign</TABLE_NAME>
  <COLUMN_NAME>project_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_devicedesign</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_devicedesign</TABLE_NAME>
  <COLUMN_NAME>isCircular</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_devicedesign</TABLE_NAME>
  <COLUMN_NAME>combinatorial</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_devicedesign</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_devicedesign</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_devicedesign</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_devicedesign</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_devicedesign"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_eugene_rule</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_eugene_rule</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_eugene_rule</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_eugene_rule</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_eugene_rule</TABLE_NAME>
  <COLUMN_NAME>devicedesign_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_eugene_rule</TABLE_NAME>
  <COLUMN_NAME>compositionalOperator</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_eugene_rule</TABLE_NAME>
  <COLUMN_NAME>operand2Number</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_eugene_rule</TABLE_NAME>
  <COLUMN_NAME>operand2IsNumber</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_eugene_rule</TABLE_NAME>
  <COLUMN_NAME>negationOperator</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_eugene_rule</TABLE_NAME>
  <COLUMN_NAME>originalRuleLine</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_eugene_rule</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_eugene_rule</TABLE_NAME>
  <COLUMN_NAME>operand2_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_eugene_rule</TABLE_NAME>
  <COLUMN_NAME>operand1_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_eugene_rule</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_eugene_rule</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_eugene_rule</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_eugene_rule"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group</TABLE_NAME>
  <COLUMN_NAME>description</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_group"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group_user</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group_user</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group_user</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group_user</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group_user</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group_user</TABLE_NAME>
  <COLUMN_NAME>group_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group_user</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group_user</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_group_user</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_group_user"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>protocol_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>project_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>clientTimeDiff</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>clobTest</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>devicedesign_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>status</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>endDate</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>devicedesign_name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>date</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>assemblyType</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>assemblyMethod</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_j5run"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>j5output</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_j5run</TABLE_NAME>
  <COLUMN_NAME>results</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_master</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_master</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_master</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_master</TABLE_NAME>
  <COLUMN_NAME>masterPlasmidList</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_master</TABLE_NAME>
  <COLUMN_NAME>masterOligoList</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_master</TABLE_NAME>
  <COLUMN_NAME>masterDirectSynthesesList</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_master</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_master</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_master</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_master</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_master</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_master"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>sequence_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>size</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>iconID</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>features</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>directionForward</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>revComp</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>endBP</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>genbankStartBP</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>FQDN</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>definitionHash</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_part"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>preferred5PrimeOverhangs</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>preferred3PrimeOverhangs</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_part</TABLE_NAME>
  <COLUMN_NAME>partSource</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_preset</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_preset</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_preset</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_preset</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_preset</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_preset</TABLE_NAME>
  <COLUMN_NAME>j5parameters</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_preset</TABLE_NAME>
  <COLUMN_NAME>presetName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_preset</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_preset</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_preset</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_preset"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_project</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_project</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_project</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_project</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_project</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_project</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_project</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_project</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_project</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_project"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein</TABLE_NAME>
  <COLUMN_NAME>shared_repo</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein</TABLE_NAME>
  <COLUMN_NAME>sequence</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein</TABLE_NAME>
  <COLUMN_NAME>size</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein</TABLE_NAME>
  <COLUMN_NAME>description</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein</TABLE_NAME>
  <COLUMN_NAME>circular</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein</TABLE_NAME>
  <COLUMN_NAME>hash</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein</TABLE_NAME>
  <COLUMN_NAME>FQDN</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_protein"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein_feature</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein_feature</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein_feature</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein_feature</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein_feature</TABLE_NAME>
  <COLUMN_NAME>protein_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein_feature</TABLE_NAME>
  <COLUMN_NAME>prot_feature_type_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein_feature</TABLE_NAME>
  <COLUMN_NAME>notes</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein_feature</TABLE_NAME>
  <COLUMN_NAME>end</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein_feature</TABLE_NAME>
  <COLUMN_NAME>start</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein_feature</TABLE_NAME>
  <COLUMN_NAME>type</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein_feature</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein_feature</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein_feature</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protein_feature</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_protein_feature"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protocol</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protocol</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protocol</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protocol</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protocol</TABLE_NAME>
  <COLUMN_NAME>contact</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protocol</TABLE_NAME>
  <COLUMN_NAME>version</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protocol</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protocol</TABLE_NAME>
  <COLUMN_NAME>assemblyMethods</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protocol</TABLE_NAME>
  <COLUMN_NAME>htmlContent</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protocol</TABLE_NAME>
  <COLUMN_NAME>author</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protocol</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protocol</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protocol</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_protocol</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_protocol"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_role</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_role</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_role</TABLE_NAME>
  <COLUMN_NAME>description</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_role</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_role</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_role</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_role</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_role"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_blacklist</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_blacklist</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_blacklist</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_blacklist</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_blacklist</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_blacklist</TABLE_NAME>
  <COLUMN_NAME>sequence_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_blacklist</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_blacklist</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_blacklist</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_seq_blacklist"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_feature</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_feature</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_feature</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_feature</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_feature</TABLE_NAME>
  <COLUMN_NAME>protein_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_feature</TABLE_NAME>
  <COLUMN_NAME>notes</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_feature</TABLE_NAME>
  <COLUMN_NAME>strand</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_feature</TABLE_NAME>
  <COLUMN_NAME>sequence_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_feature</TABLE_NAME>
  <COLUMN_NAME>end</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_feature</TABLE_NAME>
  <COLUMN_NAME>start</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_feature</TABLE_NAME>
  <COLUMN_NAME>type</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_feature</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_feature</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_feature</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_seq_feature</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_seq_feature"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>molecule_type</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>type</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>shared_repo</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>sequence</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>size</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>description</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>circular</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>hash</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>FQDN</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_sequence</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_sequence"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>alias</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>creator</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>creatorEmail</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>fundingSource</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>status</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>bioSafetyLevel</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>parentStrain</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>links</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>genotype</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>keywords</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>summary</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>references</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>intellectualProperty</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>principalInvestigator</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>selectionMarkers</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>FQDN</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_strain"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain_plasmid</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain_plasmid</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain_plasmid</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain_plasmid</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain_plasmid</TABLE_NAME>
  <COLUMN_NAME>sequence_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain_plasmid</TABLE_NAME>
  <COLUMN_NAME>strain_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain_plasmid</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain_plasmid</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_strain_plasmid</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_strain_plasmid"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_tag</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_tag</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_tag</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_tag</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_tag</TABLE_NAME>
  <COLUMN_NAME>color</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_tag</TABLE_NAME>
  <COLUMN_NAME>name</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_tag</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_tag</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_tag</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_tag</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_tag"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>masterPlasmidList</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>masterOligoList</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>masterDirectSynthesesList</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>userRestrictionEnzymeGroups</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>userAccount</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>phoneNumber</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>activeFlag</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>middleName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>token</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>activated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>verifiedEmail</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>debugAccess</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>lastAccess</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>groupType</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>groupName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>activationCode</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>email</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>lastName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>firstName</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>password</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>username</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_user"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user_role</TABLE_NAME>
  <COLUMN_NAME>dateModified</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user_role</TABLE_NAME>
  <COLUMN_NAME>dateCreated</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user_role</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user_role</TABLE_NAME>
  <COLUMN_NAME>logAction</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user_role</TABLE_NAME>
  <COLUMN_NAME>role_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user_role</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user_role</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user_role</TABLE_NAME>
  <COLUMN_NAME>logSessionId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_user_role</TABLE_NAME>
  <COLUMN_NAME>logId</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_user_role"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
 <ROW>
  <TABLE_NAME>z_winston</TABLE_NAME>
  <COLUMN_NAME>channel</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_winston</TABLE_NAME>
  <COLUMN_NAME>dateLogged</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_winston</TABLE_NAME>
  <COLUMN_NAME>metadata</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_winston</TABLE_NAME>
  <COLUMN_NAME>message</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_winston</TABLE_NAME>
  <COLUMN_NAME>level</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_winston</TABLE_NAME>
  <COLUMN_NAME>requestId</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_winston</TABLE_NAME>
  <COLUMN_NAME>user_id</COLUMN_NAME>
 </ROW>
 <ROW>
  <TABLE_NAME>z_winston</TABLE_NAME>
  <COLUMN_NAME>id</COLUMN_NAME>
  <DATA_DEFAULT>"PNY_DOWTEST_DBO"."sz_winston"."NEXTVAL"</DATA_DEFAULT>
 </ROW>
</ROWSET>
